/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_SWC1_Led_Test_.c
 * Generated on: Sat Mar 5 19:54:9 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_SWC1_Led_Test.h"


extern const Rte_CDS_SWC1_Led_Test Rte_Instance_SWC1_Led_Test;
extern const Rte_CDS_SWC1_Led_Test * const Rte_Inst_SWC1_Led_Test;


extern Uint8 SWC1_Led_Test_PP_FlagLed_Flag_Buffer;
extern Std_ReturnType SWC1_Led_Test_PP_FlagLed_Flag_Buffer_retcode;

#ifdef RTE_PTR2ARRAYBASETYPE_PASSING

DECLSPEC_EXPORT Std_ReturnType ARUnit_Write_SWC1_Led_Test_PP_FlagLed_Flag(Uint8 Flag)
{
	SWC1_Led_Test_PP_FlagLed_Flag_Buffer = Flag;
	return RTE_E_OK;
}
DECLSPEC_EXPORT Std_ReturnType ARUnit_Read_SWC1_Led_Test_PP_FlagLed_Flag(Uint8* Flag)
{
	*Flag = SWC1_Led_Test_PP_FlagLed_Flag_Buffer;
	return RTE_E_OK;
}
DECLSPEC_EXPORT void ARUnit_Write_SWC1_Led_Test_PP_FlagLed_Flag_ReturnCode(Std_ReturnType returnCode)
{
	SWC1_Led_Test_PP_FlagLed_Flag_Buffer_retcode = returnCode;
}


DECLSPEC_EXPORT void ARUnit_Trigger_SWC1_Led_Test_blink_led(void)
{
	blink_led();
}
#else // RTE_PTR2ARRAYBASETYPE_PASSING

DECLSPEC_EXPORT Std_ReturnType ARUnit_Write_SWC1_Led_Test_PP_FlagLed_Flag(Uint8 Flag)
{
	SWC1_Led_Test_PP_FlagLed_Flag_Buffer = Flag;
	return RTE_E_OK;
}
DECLSPEC_EXPORT Std_ReturnType ARUnit_Read_SWC1_Led_Test_PP_FlagLed_Flag(Uint8* Flag)
{
	*Flag = SWC1_Led_Test_PP_FlagLed_Flag_Buffer;
	return RTE_E_OK;
}
DECLSPEC_EXPORT void ARUnit_Write_SWC1_Led_Test_PP_FlagLed_Flag_ReturnCode(Std_ReturnType returnCode)
{
	SWC1_Led_Test_PP_FlagLed_Flag_Buffer_retcode = returnCode;
}


DECLSPEC_EXPORT void ARUnit_Trigger_SWC1_Led_Test_blink_led(void)
{
	blink_led();
}
#endif // RTE_PTR2ARRAYBASETYPE_PASSING
