/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_SWC1_Led_Test.h
 * Generated on: Sat Mar 5 19:54:9 EET
 ********************************************************************/

#include "Rte_SWC1_Led_Test.h"	

#ifndef ARUNIT_SWC1_LED_TEST_H
#define ARUNIT_SWC1_LED_TEST_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef false
    #define false (0)
#endif
#ifndef true
    #define true  (!false)
#endif


void ARUnit_Initialize ();

/***************************************/
/******** Delegates API  ***************/
/***************************************/

/***************************************/
/******** Flags API  *******************/
/***************************************/

#ifdef RTE_PTR2ARRAYBASETYPE_PASSING
/***************************************/
/******** Implicit API  ****************/
/***************************************/
/***************************************/
/******** Explicit API  ****************/
/***************************************/
DECLSPEC_EXPORT Std_ReturnType ARUnit_Write_SWC1_Led_Test_PP_FlagLed_Flag(Uint8 Flag);
DECLSPEC_EXPORT Std_ReturnType ARUnit_Read_SWC1_Led_Test_PP_FlagLed_Flag(Uint8* Flag);
DECLSPEC_EXPORT void ARUnit_Write_SWC1_Led_Test_PP_FlagLed_Flag_ReturnCode(Std_ReturnType returnCode);
/***************************************/
/******** Runnable Calls****************/
/***************************************/

DECLSPEC_EXPORT void ARUnit_Trigger_SWC1_Led_Test_blink_led(void);
#else // RTE_PTR2ARRAYBASETYPE_PASSING
/***************************************/
/******** Implicit API  ****************/
/***************************************/
/***************************************/
/******** Explicit API  ****************/
/***************************************/
DECLSPEC_EXPORT Std_ReturnType ARUnit_Write_SWC1_Led_Test_PP_FlagLed_Flag(Uint8 Flag);
DECLSPEC_EXPORT Std_ReturnType ARUnit_Read_SWC1_Led_Test_PP_FlagLed_Flag(Uint8* Flag);
DECLSPEC_EXPORT void ARUnit_Write_SWC1_Led_Test_PP_FlagLed_Flag_ReturnCode(Std_ReturnType returnCode);
/***************************************/
/******** Runnable Calls****************/
/***************************************/

DECLSPEC_EXPORT void ARUnit_Trigger_SWC1_Led_Test_blink_led(void);
#endif // RTE_PTR2ARRAYBASETYPE_PASSING

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ARUNIT_SWC1_LED_TEST_H */
