/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Type.h
 * Generated on: Sat Mar 5 19:54:9 EET
 ********************************************************************/

#ifndef RTE_TYPE_H
#define RTE_TYPE_H


#include "../rte_util/Rte.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/**************************** datatypes ******************************/

typedef uint8 Uint8;

/************************ enumeration types **************************/

/*************************** range types *****************************/

#define Uint8_LowerLimit ((Uint8)0)
#define Uint8_UpperLimit ((Uint8)255)

/********************* mode declaration groups ***********************/


/********************** per instance memories ************************/


/******************* implicit buffer declaration *********************/


/******************** component data structures **********************/

/*********************************************************************
 * component data structure for SWC: SWC1_Led_Test 
 *********************************************************************/
typedef struct Rte_CDS_SWC1_Led_Test
{
	/* Data Handles section*/
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
	uint8 _dummy;
} Rte_CDS_SWC1_Led_Test;


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_TYPE_H */
