/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC1_Led_Test.h
 * Generated on: Sat Mar 5 19:54:9 EET
 ********************************************************************/

#ifndef RTE_SWC1_LED_TEST_H
#define RTE_SWC1_LED_TEST_H

#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_SWC1_Led_Test * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_SWC1_Led_Test * const Rte_Inst_SWC1_Led_Test;

/************************ application errors *************************/


/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


#ifdef RTE_PTR2ARRAYBASETYPE_PASSING
/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PP_FlagLed
 * Interface:	SR_test
 * DataElement:	Flag
 *****************************************************/
extern Std_ReturnType Rte_Write_SWC1_Led_Test_PP_FlagLed_Flag (Uint8 Flag);
#ifndef IN_RTE_C
#define Rte_Write_PP_FlagLed_Flag(RTEData) \
	Rte_Write_SWC1_Led_Test_PP_FlagLed_Flag(RTEData)
#endif



/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	Run1
 * Period:		0.05
 *****************************************************/
extern void blink_led(void);


/******** ARUnit-specific function pointers for server call delegates *********/

#else // RTE_PTR2ARRAYBASETYPE_PASSING
/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PP_FlagLed
 * Interface:	SR_test
 * DataElement:	Flag
 *****************************************************/
extern Std_ReturnType Rte_Write_SWC1_Led_Test_PP_FlagLed_Flag (Uint8 Flag);
#ifndef IN_RTE_C
#define Rte_Write_PP_FlagLed_Flag(RTEData) \
	Rte_Write_SWC1_Led_Test_PP_FlagLed_Flag(RTEData)
#endif



/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	Run1
 * Period:		0.05
 *****************************************************/
extern void blink_led(void);


/******** ARUnit-specific function pointers for server call delegates *********/

#endif // RTE_PTR2ARRAYBASETYPE_PASSING

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SWC1_LED_TEST_H */
