/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC1_Led_Test_.c
 * Generated on: Sat Mar 5 19:54:9 EET
 ********************************************************************/

#include "string.h"
#include "Rte_SWC1_Led_Test.h"
#include "tp.h"
#include "tpl_os.h"



const Rte_CDS_SWC1_Led_Test Rte_Instance_SWC1_Led_Test = {
0
};

const Rte_CDS_SWC1_Led_Test * const Rte_Inst_SWC1_Led_Test = &Rte_Instance_SWC1_Led_Test;


Uint8 SWC1_Led_Test_PP_FlagLed_Flag_Buffer;
Std_ReturnType SWC1_Led_Test_PP_FlagLed_Flag_Buffer_retcode = RTE_E_OK;
Std_ReturnType SWC1_Led_Test_PP_FlagLed_Flag_Buffer_invalidate_retcode = RTE_E_OK;

#ifdef RTE_PTR2ARRAYBASETYPE_PASSING

Std_ReturnType Rte_Write_SWC1_Led_Test_PP_FlagLed_Flag (Uint8 Flag)
{
	SWC1_Led_Test_PP_FlagLed_Flag_Buffer = Flag;
	return SWC1_Led_Test_PP_FlagLed_Flag_Buffer_retcode;
}
#else // RTE_PTR2ARRAYBASETYPE_PASSING

Std_ReturnType Rte_Write_SWC1_Led_Test_PP_FlagLed_Flag (Uint8 Flag)
{

	SWC1_Led_Test_PP_FlagLed_Flag_Buffer = Flag;
	ledToggle(GREEN);
	return SWC1_Led_Test_PP_FlagLed_Flag_Buffer_retcode;
}
#endif // RTE_PTR2ARRAYBASETYPE_PASSING
