#ifndef GENERATED_ASN1SCC_CAM_H
#define GENERATED_ASN1SCC_CAM_H
/*
	Code automatically generated by asn1scc tool
	Edited by Sayed Badr:
	1- Commenting all externed variables.
	2- Minimize the V2xFac_CamMessageRootType_REQUIRED_BYTES_FOR_ENCODING from 676 to 100 Bytes.
	3- Minimze the V2xFac_CamMessageRootType_REQUIRED_BITS_FOR_ENCODING from 5407 to 800.

*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"
#include "ITS.h"


#ifdef  __cplusplus
extern "C" {
#endif

/*-- V2xFac_PublicTransportContainerType --------------------------------------------*/
typedef struct {
    V2xFac_EmbarkationStatusType embarkationStatus;
    V2xFac_PtActivationType ptActivation;

    struct {
        unsigned int ptActivation:1;
    } exist;

} V2xFac_PublicTransportContainerType;

void V2xFac_PublicTransportContainerType_Initialize(V2xFac_PublicTransportContainerType* pVal);

#define ERR_V2XFAC_PUBLICTRANSPORTCONTAINERTYPE		9108  /**/
#define ERR_V2XFAC_PUBLICTRANSPORTCONTAINERTYPE_EMBARKATIONSTATUS_2		9059  /**/
#define ERR_V2XFAC_PUBLICTRANSPORTCONTAINERTYPE_PTACTIVATION_2		9101  /**/
flag V2xFac_PublicTransportContainerType_IsConstraintValid(const V2xFac_PublicTransportContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_PUBLICTRANSPORTCONTAINERTYPE		9109  /**/
#define ERR_UPER_ENCODE_V2XFAC_PUBLICTRANSPORTCONTAINERTYPE_EMBARKATIONSTATUS_2		9060  /**/
#define ERR_UPER_ENCODE_V2XFAC_PUBLICTRANSPORTCONTAINERTYPE_PTACTIVATION_2		9102  /**/
#define V2xFac_PublicTransportContainerType_REQUIRED_BYTES_FOR_ENCODING       22
#define V2xFac_PublicTransportContainerType_REQUIRED_BITS_FOR_ENCODING        175

flag V2xFac_PublicTransportContainerType_Encode(const V2xFac_PublicTransportContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_PUBLICTRANSPORTCONTAINERTYPE		9110  /**/
#define ERR_UPER_DECODE_V2XFAC_PUBLICTRANSPORTCONTAINERTYPE_EMBARKATIONSTATUS_2		9061  /**/
#define ERR_UPER_DECODE_V2XFAC_PUBLICTRANSPORTCONTAINERTYPE_PTACTIVATION_2		9103  /**/
flag V2xFac_PublicTransportContainerType_Decode(V2xFac_PublicTransportContainerType* pVal, BitStream* pBitStrm, int* pErrCode);



/*-- V2xFac_BasicContainerType --------------------------------------------*/
typedef struct {
    V2xFac_StationTypeType stationType;
    V2xFac_ReferencePositionType referencePosition;

} V2xFac_BasicContainerType;

void V2xFac_BasicContainerType_Initialize(V2xFac_BasicContainerType* pVal);

#define ERR_V2XFAC_BASICCONTAINERTYPE		8380  /**/
#define ERR_V2XFAC_BASICCONTAINERTYPE_STATIONTYPE_2		8233  /**/
#define ERR_V2XFAC_BASICCONTAINERTYPE_REFERENCEPOSITION_2		8373  /**/
flag V2xFac_BasicContainerType_IsConstraintValid(const V2xFac_BasicContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_BASICCONTAINERTYPE		8381  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICCONTAINERTYPE_STATIONTYPE_2		8234  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICCONTAINERTYPE_REFERENCEPOSITION_2		8374  /**/
#define V2xFac_BasicContainerType_REQUIRED_BYTES_FOR_ENCODING       17
#define V2xFac_BasicContainerType_REQUIRED_BITS_FOR_ENCODING        131

flag V2xFac_BasicContainerType_Encode(const V2xFac_BasicContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_BASICCONTAINERTYPE		8382  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICCONTAINERTYPE_STATIONTYPE_2		8235  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICCONTAINERTYPE_REFERENCEPOSITION_2		8375  /**/
flag V2xFac_BasicContainerType_Decode(V2xFac_BasicContainerType* pVal, BitStream* pBitStrm, int* pErrCode);


/*-- V2xFac_DangerousGoodsContainerType --------------------------------------------*/
typedef struct {
    V2xFac_DangerousGoodsBasicType dangerousGoodsBasic;

} V2xFac_DangerousGoodsContainerType;

void V2xFac_DangerousGoodsContainerType_Initialize(V2xFac_DangerousGoodsContainerType* pVal);

#define ERR_V2XFAC_DANGEROUSGOODSCONTAINERTYPE		9164  /**/
#define ERR_V2XFAC_DANGEROUSGOODSCONTAINERTYPE_DANGEROUSGOODSBASIC_2		9157  /**/
flag V2xFac_DangerousGoodsContainerType_IsConstraintValid(const V2xFac_DangerousGoodsContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_DANGEROUSGOODSCONTAINERTYPE		9165  /**/
#define ERR_UPER_ENCODE_V2XFAC_DANGEROUSGOODSCONTAINERTYPE_DANGEROUSGOODSBASIC_2		9158  /**/
#define V2xFac_DangerousGoodsContainerType_REQUIRED_BYTES_FOR_ENCODING       1
#define V2xFac_DangerousGoodsContainerType_REQUIRED_BITS_FOR_ENCODING        5

flag V2xFac_DangerousGoodsContainerType_Encode(const V2xFac_DangerousGoodsContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_DANGEROUSGOODSCONTAINERTYPE		9166  /**/
#define ERR_UPER_DECODE_V2XFAC_DANGEROUSGOODSCONTAINERTYPE_DANGEROUSGOODSBASIC_2		9159  /**/
flag V2xFac_DangerousGoodsContainerType_Decode(V2xFac_DangerousGoodsContainerType* pVal, BitStream* pBitStrm, int* pErrCode);


/*-- V2xFac_SpecialTransportContainerType --------------------------------------------*/
typedef struct {
    V2xFac_SpecialTransportTypeType specialTransportType;
    V2xFac_LightBarSirenInUseType lightBarSirenInUse;

} V2xFac_SpecialTransportContainerType;

void V2xFac_SpecialTransportContainerType_Initialize(V2xFac_SpecialTransportContainerType* pVal);

#define ERR_V2XFAC_SPECIALTRANSPORTCONTAINERTYPE		9143  /**/
#define ERR_V2XFAC_SPECIALTRANSPORTCONTAINERTYPE_SPECIALTRANSPORTTYPE_2		9122  /**/
#define ERR_V2XFAC_SPECIALTRANSPORTCONTAINERTYPE_LIGHTBARSIRENINUSE_2		9136  /**/
flag V2xFac_SpecialTransportContainerType_IsConstraintValid(const V2xFac_SpecialTransportContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_SPECIALTRANSPORTCONTAINERTYPE		9144  /**/
#define ERR_UPER_ENCODE_V2XFAC_SPECIALTRANSPORTCONTAINERTYPE_SPECIALTRANSPORTTYPE_2		9123  /**/
#define ERR_UPER_ENCODE_V2XFAC_SPECIALTRANSPORTCONTAINERTYPE_LIGHTBARSIRENINUSE_2		9137  /**/
#define V2xFac_SpecialTransportContainerType_REQUIRED_BYTES_FOR_ENCODING       1
#define V2xFac_SpecialTransportContainerType_REQUIRED_BITS_FOR_ENCODING        6

flag V2xFac_SpecialTransportContainerType_Encode(const V2xFac_SpecialTransportContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_SPECIALTRANSPORTCONTAINERTYPE		9145  /**/
#define ERR_UPER_DECODE_V2XFAC_SPECIALTRANSPORTCONTAINERTYPE_SPECIALTRANSPORTTYPE_2		9124  /**/
#define ERR_UPER_DECODE_V2XFAC_SPECIALTRANSPORTCONTAINERTYPE_LIGHTBARSIRENINUSE_2		9138  /**/
flag V2xFac_SpecialTransportContainerType_Decode(V2xFac_SpecialTransportContainerType* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- V2xFac_RoadWorksContainerBasicType --------------------------------------------*/
typedef struct {
    V2xFac_RoadworksSubCauseCodeType roadworksSubCauseCode;
    V2xFac_LightBarSirenInUseType lightBarSirenInUse;
    V2xFac_ClosedLanesType closedLanes;

    struct {
        unsigned int roadworksSubCauseCode:1;
        unsigned int closedLanes:1;
    } exist;

} V2xFac_RoadWorksContainerBasicType;

void V2xFac_RoadWorksContainerBasicType_Initialize(V2xFac_RoadWorksContainerBasicType* pVal);

#define ERR_V2XFAC_ROADWORKSCONTAINERBASICTYPE		9241  /**/
#define ERR_V2XFAC_ROADWORKSCONTAINERBASICTYPE_ROADWORKSSUBCAUSECODE_2		9178  /**/
#define ERR_V2XFAC_ROADWORKSCONTAINERBASICTYPE_LIGHTBARSIRENINUSE_2		9192  /**/
#define ERR_V2XFAC_ROADWORKSCONTAINERBASICTYPE_CLOSEDLANES_2		9234  /**/
flag V2xFac_RoadWorksContainerBasicType_IsConstraintValid(const V2xFac_RoadWorksContainerBasicType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_ROADWORKSCONTAINERBASICTYPE		9242  /**/
#define ERR_UPER_ENCODE_V2XFAC_ROADWORKSCONTAINERBASICTYPE_ROADWORKSSUBCAUSECODE_2		9179  /**/
#define ERR_UPER_ENCODE_V2XFAC_ROADWORKSCONTAINERBASICTYPE_LIGHTBARSIRENINUSE_2		9193  /**/
#define ERR_UPER_ENCODE_V2XFAC_ROADWORKSCONTAINERBASICTYPE_CLOSEDLANES_2		9235  /**/
#define V2xFac_RoadWorksContainerBasicType_REQUIRED_BYTES_FOR_ENCODING       5
#define V2xFac_RoadWorksContainerBasicType_REQUIRED_BITS_FOR_ENCODING        33

flag V2xFac_RoadWorksContainerBasicType_Encode(const V2xFac_RoadWorksContainerBasicType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_ROADWORKSCONTAINERBASICTYPE		9243  /**/
#define ERR_UPER_DECODE_V2XFAC_ROADWORKSCONTAINERBASICTYPE_ROADWORKSSUBCAUSECODE_2		9180  /**/
#define ERR_UPER_DECODE_V2XFAC_ROADWORKSCONTAINERBASICTYPE_LIGHTBARSIRENINUSE_2		9194  /**/
#define ERR_UPER_DECODE_V2XFAC_ROADWORKSCONTAINERBASICTYPE_CLOSEDLANES_2		9236  /**/
flag V2xFac_RoadWorksContainerBasicType_Decode(V2xFac_RoadWorksContainerBasicType* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- V2xFac_RescueContainerType --------------------------------------------*/
typedef struct {
    V2xFac_LightBarSirenInUseType lightBarSirenInUse;

} V2xFac_RescueContainerType;

void V2xFac_RescueContainerType_Initialize(V2xFac_RescueContainerType* pVal);

#define ERR_V2XFAC_RESCUECONTAINERTYPE		9262  /**/
#define ERR_V2XFAC_RESCUECONTAINERTYPE_LIGHTBARSIRENINUSE_2		9255  /**/
flag V2xFac_RescueContainerType_IsConstraintValid(const V2xFac_RescueContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_RESCUECONTAINERTYPE		9263  /**/
#define ERR_UPER_ENCODE_V2XFAC_RESCUECONTAINERTYPE_LIGHTBARSIRENINUSE_2		9256  /**/
#define V2xFac_RescueContainerType_REQUIRED_BYTES_FOR_ENCODING       1
#define V2xFac_RescueContainerType_REQUIRED_BITS_FOR_ENCODING        2

flag V2xFac_RescueContainerType_Encode(const V2xFac_RescueContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_RESCUECONTAINERTYPE		9264  /**/
#define ERR_UPER_DECODE_V2XFAC_RESCUECONTAINERTYPE_LIGHTBARSIRENINUSE_2		9257  /**/
flag V2xFac_RescueContainerType_Decode(V2xFac_RescueContainerType* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- V2xFac_SafetyCarContainerType --------------------------------------------*/
typedef struct {
    V2xFac_LightBarSirenInUseType lightBarSirenInUse;
    V2xFac_CauseCodeType incidentIndication;
    V2xFac_TrafficRuleType trafficRule;
    V2xFac_SpeedLimitType speedLimit;

    struct {
        unsigned int incidentIndication:1;
        unsigned int trafficRule:1;
        unsigned int speedLimit:1;
    } exist;

} V2xFac_SafetyCarContainerType;

void V2xFac_SafetyCarContainerType_Initialize(V2xFac_SafetyCarContainerType* pVal);

#define ERR_V2XFAC_SAFETYCARCONTAINERTYPE		9430  /**/
#define ERR_V2XFAC_SAFETYCARCONTAINERTYPE_LIGHTBARSIRENINUSE_2		9353  /**/
#define ERR_V2XFAC_SAFETYCARCONTAINERTYPE_INCIDENTINDICATION_2		9395  /**/
#define ERR_V2XFAC_SAFETYCARCONTAINERTYPE_TRAFFICRULE_2		9409  /**/
#define ERR_V2XFAC_SAFETYCARCONTAINERTYPE_SPEEDLIMIT_2		9423  /**/
flag V2xFac_SafetyCarContainerType_IsConstraintValid(const V2xFac_SafetyCarContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_SAFETYCARCONTAINERTYPE		9431  /**/
#define ERR_UPER_ENCODE_V2XFAC_SAFETYCARCONTAINERTYPE_LIGHTBARSIRENINUSE_2		9354  /**/
#define ERR_UPER_ENCODE_V2XFAC_SAFETYCARCONTAINERTYPE_INCIDENTINDICATION_2		9396  /**/
#define ERR_UPER_ENCODE_V2XFAC_SAFETYCARCONTAINERTYPE_TRAFFICRULE_2		9410  /**/
#define ERR_UPER_ENCODE_V2XFAC_SAFETYCARCONTAINERTYPE_SPEEDLIMIT_2		9424  /**/
#define V2xFac_SafetyCarContainerType_REQUIRED_BYTES_FOR_ENCODING       4
#define V2xFac_SafetyCarContainerType_REQUIRED_BITS_FOR_ENCODING        31

flag V2xFac_SafetyCarContainerType_Encode(const V2xFac_SafetyCarContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_SAFETYCARCONTAINERTYPE		9432  /**/
#define ERR_UPER_DECODE_V2XFAC_SAFETYCARCONTAINERTYPE_LIGHTBARSIRENINUSE_2		9355  /**/
#define ERR_UPER_DECODE_V2XFAC_SAFETYCARCONTAINERTYPE_INCIDENTINDICATION_2		9397  /**/
#define ERR_UPER_DECODE_V2XFAC_SAFETYCARCONTAINERTYPE_TRAFFICRULE_2		9411  /**/
#define ERR_UPER_DECODE_V2XFAC_SAFETYCARCONTAINERTYPE_SPEEDLIMIT_2		9425  /**/
flag V2xFac_SafetyCarContainerType_Decode(V2xFac_SafetyCarContainerType* pVal, BitStream* pBitStrm, int* pErrCode);


/*-- V2xFac_EmergencyContainerType --------------------------------------------*/
typedef struct {
    V2xFac_LightBarSirenInUseType lightBarSirenInUse;
    V2xFac_CauseCodeType incidentIndication;
    V2xFac_EmergencyPriorityType emergencyPriority;

    struct {
        unsigned int incidentIndication:1;
        unsigned int emergencyPriority:1;
    } exist;

} V2xFac_EmergencyContainerType;

void V2xFac_EmergencyContainerType_Initialize(V2xFac_EmergencyContainerType* pVal);

#define ERR_V2XFAC_EMERGENCYCONTAINERTYPE		9339  /**/
#define ERR_V2XFAC_EMERGENCYCONTAINERTYPE_LIGHTBARSIRENINUSE_2		9276  /**/
#define ERR_V2XFAC_EMERGENCYCONTAINERTYPE_INCIDENTINDICATION_2		9318  /**/
#define ERR_V2XFAC_EMERGENCYCONTAINERTYPE_EMERGENCYPRIORITY_2		9332  /**/
flag V2xFac_EmergencyContainerType_IsConstraintValid(const V2xFac_EmergencyContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_EMERGENCYCONTAINERTYPE		9340  /**/
#define ERR_UPER_ENCODE_V2XFAC_EMERGENCYCONTAINERTYPE_LIGHTBARSIRENINUSE_2		9277  /**/
#define ERR_UPER_ENCODE_V2XFAC_EMERGENCYCONTAINERTYPE_INCIDENTINDICATION_2		9319  /**/
#define ERR_UPER_ENCODE_V2XFAC_EMERGENCYCONTAINERTYPE_EMERGENCYPRIORITY_2		9333  /**/
#define V2xFac_EmergencyContainerType_REQUIRED_BYTES_FOR_ENCODING       3
#define V2xFac_EmergencyContainerType_REQUIRED_BITS_FOR_ENCODING        22

flag V2xFac_EmergencyContainerType_Encode(const V2xFac_EmergencyContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_EMERGENCYCONTAINERTYPE		9341  /**/
#define ERR_UPER_DECODE_V2XFAC_EMERGENCYCONTAINERTYPE_LIGHTBARSIRENINUSE_2		9278  /**/
#define ERR_UPER_DECODE_V2XFAC_EMERGENCYCONTAINERTYPE_INCIDENTINDICATION_2		9320  /**/
#define ERR_UPER_DECODE_V2XFAC_EMERGENCYCONTAINERTYPE_EMERGENCYPRIORITY_2		9334  /**/
flag V2xFac_EmergencyContainerType_Decode(V2xFac_EmergencyContainerType* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- V2xFac_SpecialVehicleContainerType --------------------------------------------*/

typedef enum {
    V2xFac_SpecialVehicleContainerType_NONE,
    publicTransportContainer_PRESENT,
    specialTransportContainer_PRESENT,
    dangerousGoodsContainer_PRESENT,
    roadWorksContainerBasic_PRESENT,
    rescueContainer_PRESENT,
    emergencyContainer_PRESENT,
    safetyCarContainer_PRESENT
} V2xFac_SpecialVehicleContainerType_selection;


typedef struct {
    V2xFac_SpecialVehicleContainerType_selection kind;

    union {
        V2xFac_PublicTransportContainerType publicTransportContainer;
        V2xFac_SpecialTransportContainerType specialTransportContainer;
        V2xFac_DangerousGoodsContainerType dangerousGoodsContainer;
        V2xFac_RoadWorksContainerBasicType roadWorksContainerBasic;
        V2xFac_RescueContainerType rescueContainer;
        V2xFac_EmergencyContainerType emergencyContainer;
        V2xFac_SafetyCarContainerType safetyCarContainer;
    } u;
} V2xFac_SpecialVehicleContainerType;

void V2xFac_SpecialVehicleContainerType_Initialize(V2xFac_SpecialVehicleContainerType* pVal);

#define ERR_V2XFAC_SPECIALVEHICLECONTAINERTYPE		8219  /**/
#define ERR_V2XFAC_SPECIALVEHICLECONTAINERTYPE_PUBLICTRANSPORTCONTAINER_2		7848  /**/
#define ERR_V2XFAC_SPECIALVEHICLECONTAINERTYPE_SPECIALTRANSPORTCONTAINER_2		7890  /**/
#define ERR_V2XFAC_SPECIALVEHICLECONTAINERTYPE_DANGEROUSGOODSCONTAINER_2		7918  /**/
#define ERR_V2XFAC_SPECIALVEHICLECONTAINERTYPE_ROADWORKSCONTAINERBASIC_2		8002  /**/
#define ERR_V2XFAC_SPECIALVEHICLECONTAINERTYPE_RESCUECONTAINER_2		8030  /**/
#define ERR_V2XFAC_SPECIALVEHICLECONTAINERTYPE_EMERGENCYCONTAINER_2		8114  /**/
#define ERR_V2XFAC_SPECIALVEHICLECONTAINERTYPE_SAFETYCARCONTAINER_2		8212  /**/
flag V2xFac_SpecialVehicleContainerType_IsConstraintValid(const V2xFac_SpecialVehicleContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE		8220  /**/
#define ERR_UPER_ENCODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE_PUBLICTRANSPORTCONTAINER_2		7849  /**/
#define ERR_UPER_ENCODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE_SPECIALTRANSPORTCONTAINER_2		7891  /**/
#define ERR_UPER_ENCODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE_DANGEROUSGOODSCONTAINER_2		7919  /**/
#define ERR_UPER_ENCODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE_ROADWORKSCONTAINERBASIC_2		8003  /**/
#define ERR_UPER_ENCODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE_RESCUECONTAINER_2		8031  /**/
#define ERR_UPER_ENCODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE_EMERGENCYCONTAINER_2		8115  /**/
#define ERR_UPER_ENCODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE_SAFETYCARCONTAINER_2		8213  /**/
#define V2xFac_SpecialVehicleContainerType_REQUIRED_BYTES_FOR_ENCODING       23
#define V2xFac_SpecialVehicleContainerType_REQUIRED_BITS_FOR_ENCODING        178

flag V2xFac_SpecialVehicleContainerType_Encode(const V2xFac_SpecialVehicleContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE		8221  /**/
#define ERR_UPER_DECODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE_PUBLICTRANSPORTCONTAINER_2		7850  /**/
#define ERR_UPER_DECODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE_SPECIALTRANSPORTCONTAINER_2		7892  /**/
#define ERR_UPER_DECODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE_DANGEROUSGOODSCONTAINER_2		7920  /**/
#define ERR_UPER_DECODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE_ROADWORKSCONTAINERBASIC_2		8004  /**/
#define ERR_UPER_DECODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE_RESCUECONTAINER_2		8032  /**/
#define ERR_UPER_DECODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE_EMERGENCYCONTAINER_2		8116  /**/
#define ERR_UPER_DECODE_V2XFAC_SPECIALVEHICLECONTAINERTYPE_SAFETYCARCONTAINER_2		8214  /**/
flag V2xFac_SpecialVehicleContainerType_Decode(V2xFac_SpecialVehicleContainerType* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- V2xFac_BasicVehicleContainerLowFrequencyType --------------------------------------------*/
typedef struct {
    V2xFac_VehicleRoleType vehicleRole;
    V2xFac_ExteriorLightsType exteriorLights;
    V2xFac_PathHistoryType pathHistory;

} V2xFac_BasicVehicleContainerLowFrequencyType;

void V2xFac_BasicVehicleContainerLowFrequencyType_Initialize(V2xFac_BasicVehicleContainerLowFrequencyType* pVal);

#define ERR_V2XFAC_BASICVEHICLECONTAINERLOWFREQUENCYTYPE		9045  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERLOWFREQUENCYTYPE_VEHICLEROLE_2		8926  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERLOWFREQUENCYTYPE_EXTERIORLIGHTS_2		8940  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERLOWFREQUENCYTYPE_PATHHISTORY_2		9038  /**/
flag V2xFac_BasicVehicleContainerLowFrequencyType_IsConstraintValid(const V2xFac_BasicVehicleContainerLowFrequencyType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERLOWFREQUENCYTYPE		9046  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERLOWFREQUENCYTYPE_VEHICLEROLE_2		8927  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERLOWFREQUENCYTYPE_EXTERIORLIGHTS_2		8941  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERLOWFREQUENCYTYPE_PATHHISTORY_2		9039  /**/
#define V2xFac_BasicVehicleContainerLowFrequencyType_REQUIRED_BYTES_FOR_ENCODING       343
#define V2xFac_BasicVehicleContainerLowFrequencyType_REQUIRED_BITS_FOR_ENCODING        2738

flag V2xFac_BasicVehicleContainerLowFrequencyType_Encode(const V2xFac_BasicVehicleContainerLowFrequencyType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERLOWFREQUENCYTYPE		9047  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERLOWFREQUENCYTYPE_VEHICLEROLE_2		8928  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERLOWFREQUENCYTYPE_EXTERIORLIGHTS_2		8942  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERLOWFREQUENCYTYPE_PATHHISTORY_2		9040  /**/
flag V2xFac_BasicVehicleContainerLowFrequencyType_Decode(V2xFac_BasicVehicleContainerLowFrequencyType* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- V2xFac_LowFrequencyContainerType --------------------------------------------*/

typedef enum {
    V2xFac_LowFrequencyContainerType_NONE,
    basicVehicleContainerLowFrequency_PRESENT
} V2xFac_LowFrequencyContainerType_selection;


typedef struct {
    V2xFac_LowFrequencyContainerType_selection kind;

    union {
        V2xFac_BasicVehicleContainerLowFrequencyType basicVehicleContainerLowFrequency;
    } u;
} V2xFac_LowFrequencyContainerType;

void V2xFac_LowFrequencyContainerType_Initialize(V2xFac_LowFrequencyContainerType* pVal);

#define ERR_V2XFAC_LOWFREQUENCYCONTAINERTYPE		7778  /**/
#define ERR_V2XFAC_LOWFREQUENCYCONTAINERTYPE_BASICVEHICLECONTAINERLOWFREQUENCY_2		7771  /**/
flag V2xFac_LowFrequencyContainerType_IsConstraintValid(const V2xFac_LowFrequencyContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_LOWFREQUENCYCONTAINERTYPE		7779  /**/
#define ERR_UPER_ENCODE_V2XFAC_LOWFREQUENCYCONTAINERTYPE_BASICVEHICLECONTAINERLOWFREQUENCY_2		7772  /**/
#define V2xFac_LowFrequencyContainerType_REQUIRED_BYTES_FOR_ENCODING       343
#define V2xFac_LowFrequencyContainerType_REQUIRED_BITS_FOR_ENCODING        2738

flag V2xFac_LowFrequencyContainerType_Encode(const V2xFac_LowFrequencyContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_LOWFREQUENCYCONTAINERTYPE		7780  /**/
#define ERR_UPER_DECODE_V2XFAC_LOWFREQUENCYCONTAINERTYPE_BASICVEHICLECONTAINERLOWFREQUENCY_2		7773  /**/
flag V2xFac_LowFrequencyContainerType_Decode(V2xFac_LowFrequencyContainerType* pVal, BitStream* pBitStrm, int* pErrCode);


/*-- V2xFac_RSUContainerHighFrequencyType --------------------------------------------*/
typedef struct {
    V2xFac_ProtectedCommunicationZonesRSUType protectedCommunicationZonesRSU;

    struct {
        unsigned int protectedCommunicationZonesRSU:1;
    } exist;

} V2xFac_RSUContainerHighFrequencyType;

void V2xFac_RSUContainerHighFrequencyType_Initialize(V2xFac_RSUContainerHighFrequencyType* pVal);

#define ERR_V2XFAC_RSUCONTAINERHIGHFREQUENCYTYPE		9549  /**/
#define ERR_V2XFAC_RSUCONTAINERHIGHFREQUENCYTYPE_PROTECTEDCOMMUNICATIONZONESRSU_2		9542  /**/
flag V2xFac_RSUContainerHighFrequencyType_IsConstraintValid(const V2xFac_RSUContainerHighFrequencyType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_RSUCONTAINERHIGHFREQUENCYTYPE		9550  /**/
#define ERR_UPER_ENCODE_V2XFAC_RSUCONTAINERHIGHFREQUENCYTYPE_PROTECTEDCOMMUNICATIONZONESRSU_2		9543  /**/
#define V2xFac_RSUContainerHighFrequencyType_REQUIRED_BYTES_FOR_ENCODING       287
#define V2xFac_RSUContainerHighFrequencyType_REQUIRED_BITS_FOR_ENCODING        2293

flag V2xFac_RSUContainerHighFrequencyType_Encode(const V2xFac_RSUContainerHighFrequencyType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_RSUCONTAINERHIGHFREQUENCYTYPE		9551  /**/
#define ERR_UPER_DECODE_V2XFAC_RSUCONTAINERHIGHFREQUENCYTYPE_PROTECTEDCOMMUNICATIONZONESRSU_2		9544  /**/
flag V2xFac_RSUContainerHighFrequencyType_Decode(V2xFac_RSUContainerHighFrequencyType* pVal, BitStream* pBitStrm, int* pErrCode);

/*-- V2xFac_BasicVehicleContainerHighFrequencyType --------------------------------------------*/
typedef struct {
    V2xFac_HeadingType heading;
    V2xFac_SpeedType speed;
    V2xFac_DriveDirectionType driveDirection;
    V2xFac_VehicleLengthType vehicleLength;
    V2xFac_VehicleWidthType vehicleWidth;
    V2xFac_LongitudinalAccelerationType longitudinalAcceleration;
    V2xFac_CurvatureType curvature;
    V2xFac_CurvatureCalculationModeType curvatureCalculationMode;
    V2xFac_YawRateType yawRate;
    V2xFac_AccelerationControlType accelerationControl;
    V2xFac_LanePositionType lanePosition;
    V2xFac_SteeringWheelAngleType steeringWheelAngle;
    V2xFac_LateralAccelerationType lateralAcceleration;
    V2xFac_VerticalAccelerationType verticalAcceleration;
    V2xFac_PerformanceClassType performanceClass;
    V2xFac_CenDsrcTollingZoneType cenDsrcTollingZone;

    struct {
        unsigned int accelerationControl:1;
        unsigned int lanePosition:1;
        unsigned int steeringWheelAngle:1;
        unsigned int lateralAcceleration:1;
        unsigned int verticalAcceleration:1;
        unsigned int performanceClass:1;
        unsigned int cenDsrcTollingZone:1;
    } exist;

} V2xFac_BasicVehicleContainerHighFrequencyType;

void V2xFac_BasicVehicleContainerHighFrequencyType_Initialize(V2xFac_BasicVehicleContainerHighFrequencyType* pVal);

#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE		8912  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_HEADING_2		8422  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_SPEED_2		8464  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_DRIVEDIRECTION_2		8478  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_VEHICLELENGTH_2		8520  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_VEHICLEWIDTH_2		8534  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_LONGITUDINALACCELERATION_2		8576  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_CURVATURE_2		8618  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_CURVATURECALCULATIONMODE_2		8632  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_YAWRATE_2		8674  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_ACCELERATIONCONTROL_2		8688  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_LANEPOSITION_2		8702  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_STEERINGWHEELANGLE_2		8744  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_LATERALACCELERATION_2		8786  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_VERTICALACCELERATION_2		8828  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_PERFORMANCECLASS_2		8842  /**/
#define ERR_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_CENDSRCTOLLINGZONE_2		8905  /**/
flag V2xFac_BasicVehicleContainerHighFrequencyType_IsConstraintValid(const V2xFac_BasicVehicleContainerHighFrequencyType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE		8913  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_HEADING_2		8423  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_SPEED_2		8465  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_DRIVEDIRECTION_2		8479  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_VEHICLELENGTH_2		8521  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_VEHICLEWIDTH_2		8535  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_LONGITUDINALACCELERATION_2		8577  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_CURVATURE_2		8619  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_CURVATURECALCULATIONMODE_2		8633  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_YAWRATE_2		8675  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_ACCELERATIONCONTROL_2		8689  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_LANEPOSITION_2		8703  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_STEERINGWHEELANGLE_2		8745  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_LATERALACCELERATION_2		8787  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_VERTICALACCELERATION_2		8829  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_PERFORMANCECLASS_2		8843  /**/
#define ERR_UPER_ENCODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_CENDSRCTOLLINGZONE_2		8906  /**/
#define V2xFac_BasicVehicleContainerHighFrequencyType_REQUIRED_BYTES_FOR_ENCODING       35 
#define V2xFac_BasicVehicleContainerHighFrequencyType_REQUIRED_BITS_FOR_ENCODING        279

flag V2xFac_BasicVehicleContainerHighFrequencyType_Encode(const V2xFac_BasicVehicleContainerHighFrequencyType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE		8914  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_HEADING_2		8424  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_SPEED_2		8466  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_DRIVEDIRECTION_2		8480  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_VEHICLELENGTH_2		8522  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_VEHICLEWIDTH_2		8536  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_LONGITUDINALACCELERATION_2		8578  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_CURVATURE_2		8620  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_CURVATURECALCULATIONMODE_2		8634  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_YAWRATE_2		8676  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_ACCELERATIONCONTROL_2		8690  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_LANEPOSITION_2		8704  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_STEERINGWHEELANGLE_2		8746  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_LATERALACCELERATION_2		8788  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_VERTICALACCELERATION_2		8830  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_PERFORMANCECLASS_2		8844  /**/
#define ERR_UPER_DECODE_V2XFAC_BASICVEHICLECONTAINERHIGHFREQUENCYTYPE_CENDSRCTOLLINGZONE_2		8907  /**/
flag V2xFac_BasicVehicleContainerHighFrequencyType_Decode(V2xFac_BasicVehicleContainerHighFrequencyType* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- V2xFac_HighFrequencyContainerType --------------------------------------------*/

typedef enum {
    V2xFac_HighFrequencyContainerType_NONE,
    basicVehicleContainerHighFrequency_PRESENT,
    rsuContainerHighFrequency_PRESENT 
} V2xFac_HighFrequencyContainerType_selection;


typedef struct {
    V2xFac_HighFrequencyContainerType_selection kind;
    
    union {
        V2xFac_BasicVehicleContainerHighFrequencyType basicVehicleContainerHighFrequency;
        V2xFac_RSUContainerHighFrequencyType rsuContainerHighFrequency;
    } u; 
} V2xFac_HighFrequencyContainerType;

void V2xFac_HighFrequencyContainerType_Initialize(V2xFac_HighFrequencyContainerType* pVal);

#define ERR_V2XFAC_HIGHFREQUENCYCONTAINERTYPE		7631  /**/
#define ERR_V2XFAC_HIGHFREQUENCYCONTAINERTYPE_BASICVEHICLECONTAINERHIGHFREQUENCY_2		7498  /**/
#define ERR_V2XFAC_HIGHFREQUENCYCONTAINERTYPE_RSUCONTAINERHIGHFREQUENCY_2		7624  /**/
flag V2xFac_HighFrequencyContainerType_IsConstraintValid(const V2xFac_HighFrequencyContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_HIGHFREQUENCYCONTAINERTYPE		7632  /**/
#define ERR_UPER_ENCODE_V2XFAC_HIGHFREQUENCYCONTAINERTYPE_BASICVEHICLECONTAINERHIGHFREQUENCY_2		7499  /**/
#define ERR_UPER_ENCODE_V2XFAC_HIGHFREQUENCYCONTAINERTYPE_RSUCONTAINERHIGHFREQUENCY_2		7625  /**/
#define V2xFac_HighFrequencyContainerType_REQUIRED_BYTES_FOR_ENCODING       287 
#define V2xFac_HighFrequencyContainerType_REQUIRED_BITS_FOR_ENCODING        2294

flag V2xFac_HighFrequencyContainerType_Encode(const V2xFac_HighFrequencyContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_HIGHFREQUENCYCONTAINERTYPE		7633  /**/
#define ERR_UPER_DECODE_V2XFAC_HIGHFREQUENCYCONTAINERTYPE_BASICVEHICLECONTAINERHIGHFREQUENCY_2		7500  /**/
#define ERR_UPER_DECODE_V2XFAC_HIGHFREQUENCYCONTAINERTYPE_RSUCONTAINERHIGHFREQUENCY_2		7626  /**/
flag V2xFac_HighFrequencyContainerType_Decode(V2xFac_HighFrequencyContainerType* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- V2xFac_CamParametersType --------------------------------------------*/
typedef struct {
    V2xFac_BasicContainerType basicContainer;
    V2xFac_HighFrequencyContainerType highFrequencyContainer;
    V2xFac_LowFrequencyContainerType lowFrequencyContainer;
    V2xFac_SpecialVehicleContainerType specialVehicleContainer;

    struct {
        unsigned int lowFrequencyContainer:1;
        unsigned int specialVehicleContainer:1;
    } exist;

} V2xFac_CamParametersType;

void V2xFac_CamParametersType_Initialize(V2xFac_CamParametersType* pVal);

#define ERR_V2XFAC_CAMPARAMETERSTYPE		6959  /**/
#define ERR_V2XFAC_CAMPARAMETERSTYPE_BASICCONTAINER_2		5671  /**/
#define ERR_V2XFAC_CAMPARAMETERSTYPE_HIGHFREQUENCYCONTAINER_2		6350  /**/
#define ERR_V2XFAC_CAMPARAMETERSTYPE_LOWFREQUENCYCONTAINER_2		6504  /**/
#define ERR_V2XFAC_CAMPARAMETERSTYPE_SPECIALVEHICLECONTAINER_2		6952  /**/
flag V2xFac_CamParametersType_IsConstraintValid(const V2xFac_CamParametersType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_CAMPARAMETERSTYPE		6960  /**/
#define ERR_UPER_ENCODE_V2XFAC_CAMPARAMETERSTYPE_BASICCONTAINER_2		5672  /**/
#define ERR_UPER_ENCODE_V2XFAC_CAMPARAMETERSTYPE_HIGHFREQUENCYCONTAINER_2		6351  /**/
#define ERR_UPER_ENCODE_V2XFAC_CAMPARAMETERSTYPE_LOWFREQUENCYCONTAINER_2		6505  /**/
#define ERR_UPER_ENCODE_V2XFAC_CAMPARAMETERSTYPE_SPECIALVEHICLECONTAINER_2		6953  /**/
#define V2xFac_CamParametersType_REQUIRED_BYTES_FOR_ENCODING       668 
#define V2xFac_CamParametersType_REQUIRED_BITS_FOR_ENCODING        5343

flag V2xFac_CamParametersType_Encode(const V2xFac_CamParametersType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_CAMPARAMETERSTYPE		6961  /**/
#define ERR_UPER_DECODE_V2XFAC_CAMPARAMETERSTYPE_BASICCONTAINER_2		5673  /**/
#define ERR_UPER_DECODE_V2XFAC_CAMPARAMETERSTYPE_HIGHFREQUENCYCONTAINER_2		6352  /**/
#define ERR_UPER_DECODE_V2XFAC_CAMPARAMETERSTYPE_LOWFREQUENCYCONTAINER_2		6506  /**/
#define ERR_UPER_DECODE_V2XFAC_CAMPARAMETERSTYPE_SPECIALVEHICLECONTAINER_2		6954  /**/
flag V2xFac_CamParametersType_Decode(V2xFac_CamParametersType* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint V2xFac_GenerationDeltaTime;


void V2xFac_GenerationDeltaTime_Initialize(V2xFac_GenerationDeltaTime* pVal);

#define ERR_V2XFAC_GENERATIONDELTATIME		9556  /**/
flag V2xFac_GenerationDeltaTime_IsConstraintValid(const V2xFac_GenerationDeltaTime* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_GENERATIONDELTATIME		9557  /**/
#define V2xFac_GenerationDeltaTime_REQUIRED_BYTES_FOR_ENCODING       2 
#define V2xFac_GenerationDeltaTime_REQUIRED_BITS_FOR_ENCODING        16

flag V2xFac_GenerationDeltaTime_Encode(const V2xFac_GenerationDeltaTime* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_GENERATIONDELTATIME		9558  /**/
flag V2xFac_GenerationDeltaTime_Decode(V2xFac_GenerationDeltaTime* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- V2xFac_CoopAwarenessType --------------------------------------------*/
typedef struct {
    V2xFac_GenerationDeltaTime generationDeltaTime;
    V2xFac_CamParametersType camParameters;

} V2xFac_CoopAwarenessType;

void V2xFac_CoopAwarenessType_Initialize(V2xFac_CoopAwarenessType* pVal);

#define ERR_V2XFAC_COOPAWARENESSTYPE		5503  /**/
#define ERR_V2XFAC_COOPAWARENESSTYPE_GENERATIONDELTATIME_2		4033  /**/
#define ERR_V2XFAC_COOPAWARENESSTYPE_CAMPARAMETERS_2		5496  /**/
flag V2xFac_CoopAwarenessType_IsConstraintValid(const V2xFac_CoopAwarenessType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_COOPAWARENESSTYPE		5504  /**/
#define ERR_UPER_ENCODE_V2XFAC_COOPAWARENESSTYPE_GENERATIONDELTATIME_2		4034  /**/
#define ERR_UPER_ENCODE_V2XFAC_COOPAWARENESSTYPE_CAMPARAMETERS_2		5497  /**/
#define V2xFac_CoopAwarenessType_REQUIRED_BYTES_FOR_ENCODING       670 
#define V2xFac_CoopAwarenessType_REQUIRED_BITS_FOR_ENCODING        5359

flag V2xFac_CoopAwarenessType_Encode(const V2xFac_CoopAwarenessType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_COOPAWARENESSTYPE		5505  /**/
#define ERR_UPER_DECODE_V2XFAC_COOPAWARENESSTYPE_GENERATIONDELTATIME_2		4035  /**/
#define ERR_UPER_DECODE_V2XFAC_COOPAWARENESSTYPE_CAMPARAMETERS_2		5498  /**/
flag V2xFac_CoopAwarenessType_Decode(V2xFac_CoopAwarenessType* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- V2xFac_CamMessageRootType --------------------------------------------*/
typedef struct {
    V2xFac_ItsPduHeaderType itsPduHeader;
    V2xFac_CoopAwarenessType coopAwareness;

} V2xFac_CamMessageRootType;

void V2xFac_CamMessageRootType_Initialize(V2xFac_CamMessageRootType* pVal);

#define ERR_V2XFAC_CAMMESSAGEROOTTYPE		4019  /**/
#define ERR_V2XFAC_CAMMESSAGEROOTTYPE_ITSPDUHEADER_2		2521  /**/
#define ERR_V2XFAC_CAMMESSAGEROOTTYPE_COOPAWARENESS_2		4012  /**/
flag V2xFac_CamMessageRootType_IsConstraintValid(const V2xFac_CamMessageRootType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_CAMMESSAGEROOTTYPE		4020  /**/
#define ERR_UPER_ENCODE_V2XFAC_CAMMESSAGEROOTTYPE_ITSPDUHEADER_2		2522  /**/
#define ERR_UPER_ENCODE_V2XFAC_CAMMESSAGEROOTTYPE_COOPAWARENESS_2		4013  /**/

/* --------------------------------------------------------------------------
 		Edited Line (Decreasing the size of the CAM buffer in bytes)
  ------------------------------------------------------------------------ */
#define V2xFac_CamMessageRootType_REQUIRED_BYTES_FOR_ENCODING       676

/*	Edited Line (Decreasing the size of the CAM buffer in bits)
------------------------------------------------------------------------ */
#define V2xFac_CamMessageRootType_REQUIRED_BITS_FOR_ENCODING        5408
/* ----------------------------------------------------------------------- */

flag V2xFac_CamMessageRootType_Encode(const V2xFac_CamMessageRootType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_CAMMESSAGEROOTTYPE		4021  /**/
#define ERR_UPER_DECODE_V2XFAC_CAMMESSAGEROOTTYPE_ITSPDUHEADER_2		2523  /**/
#define ERR_UPER_DECODE_V2XFAC_CAMMESSAGEROOTTYPE_COOPAWARENESS_2		4014  /**/
flag V2xFac_CamMessageRootType_Decode(V2xFac_CamMessageRootType* pVal, BitStream* pBitStrm, int* pErrCode);

//extern const V2xFac_LongitudeType V2xFac_LongitudeType_v2XFAC_LONGITUDE_TYPE_ONE_MICRO_DEGREE_EAST;
//extern const V2xFac_LongitudeType V2xFac_LongitudeType_v2XFAC_LONGITUDE_TYPE_ONE_MICRO_DEGREE_WEST;
//extern const V2xFac_LongitudeType V2xFac_LongitudeType_v2XFAC_LONGITUDE_TYPE_UNAVAILABLE;
//extern const V2xFac_LatitudeType V2xFac_LatitudeType_v2XFAC_LATITUDE_TYPE_ONE_MICRO_DEGREE_NORTH;
//extern const V2xFac_LatitudeType V2xFac_LatitudeType_v2XFAC_LATITUDE_TYPE_ONE_MICRO_DEGREE_SOUTH;
//extern const V2xFac_LatitudeType V2xFac_LatitudeType_v2XFAC_LATITUDE_UNAVAILABLE;
//extern const V2xFac_AltitudeValueType V2xFac_AltitudeValueType_v2XFAC_ALTITUDE_VALUE_TYPE_REFERNCE_ELLIPSOID_SURFACE;
//extern const V2xFac_AltitudeValueType V2xFac_AltitudeValueType_v2XFAC_ALTITUDE_VALUE_TYPE_ONE_CENTIMETER;
//extern const V2xFac_AltitudeValueType V2xFac_AltitudeValueType_v2XFAC_ALTITUDE_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_DeltaLongitudeType V2xFac_DeltaLongitudeType_v2XFAC_DELTA_LONGITUDE_TYPE_ONE_MICRO_DEGREE_EAST;
//extern const V2xFac_DeltaLongitudeType V2xFac_DeltaLongitudeType_v2XFAC_DELTA_LONGITUDE_TYPE_ONE_MICRO_DEGREE_WEST;
//extern const V2xFac_DeltaLongitudeType V2xFac_DeltaLongitudeType_v2XFAC_DELTA_LONGITUDE_TYPE_UNAVAILABLE;
//extern const V2xFac_DeltaLatitudeType V2xFac_DeltaLatitudeType_v2XFAC_DELTA_LATITUDE_TYPE_ONE_MICRO_DEGREE_NORTH;
//extern const V2xFac_DeltaLatitudeType V2xFac_DeltaLatitudeType_v2XFAC_DELTA_LATITUDE_TYPE_ONE_MICRO_DEGREE_SOUTH;
//extern const V2xFac_DeltaLatitudeType V2xFac_DeltaLatitudeType_v2XFAC_DELTA_LATITUDE_TYPE_UNAVAILABLE;
//extern const V2xFac_DeltaAltitudeType V2xFac_DeltaAltitudeType_v2XFAC_DELTA_ALTITUDE_TYPE_ONE_CENTIMETER_UP;
//extern const V2xFac_DeltaAltitudeType V2xFac_DeltaAltitudeType_v2XFAC_DELTA_ALTITUDE_TYPE_ONE_CENTIMETER_DOWN;
//extern const V2xFac_DeltaAltitudeType V2xFac_DeltaAltitudeType_v2XFAC_DELTA_ALTITUDE_TYPE_UNAVAILABLE;
//extern const V2xFac_PathDeltaTimeType V2xFac_PathDeltaTimeType_v2XFAC_PATH_DELTA_TIME_TYPE_TEN_MILLI_SECONDS_PAST;
//extern const V2xFac_PtActivationTypeType V2xFac_PtActivationTypeType_v2XFAC_PT_ACTIVATION_TYPE_TYPE_UNDEFINED_CODING_TYPE;
//extern const V2xFac_PtActivationTypeType V2xFac_PtActivationTypeType_v2XFAC_PT_ACTIVATION_TYPE_TYPE_R09_16_CODING_TYPE;
//extern const V2xFac_PtActivationTypeType V2xFac_PtActivationTypeType_v2XFAC_PT_ACTIVATION_TYPE_TYPE_VDV_50149_CODING_TYPE;
//extern const V2xFac_SemiAxisLengthType V2xFac_SemiAxisLengthType_v2XFAC_SEMI_AXIS_LENGTH_TYPE_ONE_CENTIMETER;
//extern const V2xFac_SemiAxisLengthType V2xFac_SemiAxisLengthType_v2XFAC_SEMI_AXIS_LENGTH_TYPE_OUT_OF_RANGE;
//extern const V2xFac_SemiAxisLengthType V2xFac_SemiAxisLengthType_v2XFAC_SEMI_AXIS_LENGTH_TYPE_UNAVAILABLE;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_RESERVED;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_TRAFFIC_CONDITION;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_ACCIDENT;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_ROAD_WORKS;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_ADVERSE_WEATHER_CONDITION_ADHESION;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_HAZARDOUS_LOCATION_SURFACE_CONDITION;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_HAZARDOUS_LOCATION_OBSTACLE_ONT_THE_ROAD;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_HAZARDOUS_LOCATION_ANIMAL_ON_THE_ROAD;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_HAZARDOUS_LOCATION_HUMAN_ON_THE_ROAD;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_WRONG_WAY_DRIVING;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_RESCUE_AND_RECOVERY_WORK_IN_PROGRESS;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_ADVERSE_WEATHER_CONDITION_VISIBILITY;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_ADVERSE_WEATHER_CONDITION_PRECIPTION;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_SLOW_VEHICLE;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_DANGEROUS_END_OF_QUEUE;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_VEHICLE_BREAK_DOWN;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_POST_CRASH;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_HUMAN_PROBLEM;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_STATIONARY_VEHICLE;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_EMERGENCY_VEHICLE_APPROACHING;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_HAZARDOUS_LOCATION_DANGEROUS_CURVE;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_COLLISION_RISK;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_SIGNAL_VIOLATION;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_DANGEROUS_SITUATION;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_INCREASED_VOLUME_OF_TRAFFIC;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_TRAFFIC_JAM_SLOWLY_INCREASING;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_TRAFFIC_JAM_INCREASING;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_TRAFFIC_JAM_STRONGLY_INCREASING;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_TRAFFIC_STATIONERY;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_TRAFFIC_JAM_SLIGHTLY_DECREASING;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_TRAFFIC_JAM_DECREASING;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_TRAFFIC_JAM_STRONGLY_DECREASING;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_MULTI_VEHICLE_ACCIDENT;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_HEAVY_ACCIDENT;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_ACCIDENT_INVOLVING_LORRY;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_ACCIDENT_INVOLVING_BUS;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_ACCIDENT_INVOLVING_HAZARDOUS_MATERIALS;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_ACCIDENT_ON_OPPOSITE_LANE;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_UNSECURED_ACCIDENT;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_ASSISTANCE_REQUESTED;
//extern const V2xFac_RoadworksSubCauseCodeType V2xFac_RoadworksSubCauseCodeType_v2XFAC_ROAD_WORKS_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_RoadworksSubCauseCodeType V2xFac_RoadworksSubCauseCodeType_v2XFAC_ROAD_WORKS_SUB_CAUSE_CODE_TYPE_MAJOR_ROAD_WORKS;
//extern const V2xFac_RoadworksSubCauseCodeType V2xFac_RoadworksSubCauseCodeType_v2XFAC_ROAD_WORKS_SUB_CAUSE_CODE_TYPE_ROAD_MARKING_WORK;
//extern const V2xFac_RoadworksSubCauseCodeType V2xFac_RoadworksSubCauseCodeType_v2XFAC_ROAD_WORKS_SUB_CAUSE_CODE_TYPE_SLOW_MOVING_ROAD_MAINTENANCE;
//extern const V2xFac_RoadworksSubCauseCodeType V2xFac_RoadworksSubCauseCodeType_v2XFAC_ROAD_WORKS_SUB_CAUSE_CODE_TYPE_SHORT_TERM_STATIONARY_ROADWORKS;
//extern const V2xFac_RoadworksSubCauseCodeType V2xFac_RoadworksSubCauseCodeType_v2XFAC_ROAD_WORKS_SUB_CAUSE_CODE_TYPE_STREET_CLEANING;
//extern const V2xFac_RoadworksSubCauseCodeType V2xFac_RoadworksSubCauseCodeType_v2XFAC_ROAD_WORKS_SUB_CAUSE_CODE_TYPE_WINTER_SERVICE;
//extern const V2xFac_HumanPresenceOnTheRoadSubCauseCodeType V2xFac_HumanPresenceOnTheRoadSubCauseCodeType_v2XFAC_HUMAN_PRESENCE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_HumanPresenceOnTheRoadSubCauseCodeType V2xFac_HumanPresenceOnTheRoadSubCauseCodeType_v2XFAC_HUMAN_PRESENCE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_CHILDREN_ON_ROADWAY;
//extern const V2xFac_HumanPresenceOnTheRoadSubCauseCodeType V2xFac_HumanPresenceOnTheRoadSubCauseCodeType_v2XFAC_HUMAN_PRESENCE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_CYCLIST_ON_ROADWAY;
//extern const V2xFac_HumanPresenceOnTheRoadSubCauseCodeType V2xFac_HumanPresenceOnTheRoadSubCauseCodeType_v2XFAC_HUMAN_PRESENCE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_MOTORCYCLIST_ON_ROADWAY;
//extern const V2xFac_WrongWayDrivingSubCauseCodeType V2xFac_WrongWayDrivingSubCauseCodeType_v2XFAC_WRONGWAY_DRIVING_SUB_CAUSECODE_TYPE_UNAVAILABLE;
//extern const V2xFac_WrongWayDrivingSubCauseCodeType V2xFac_WrongWayDrivingSubCauseCodeType_v2XFAC_WRONGWAY_DRIVING_SUB_CAUSECODE_TYPE_WRONG_LANE;
//extern const V2xFac_WrongWayDrivingSubCauseCodeType V2xFac_WrongWayDrivingSubCauseCodeType_v2XFAC_WRONGWAY_DRIVING_SUB_CAUSECODE_TYPE_WRONG_DIRECTION;
//extern const V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_TYPE_STRONG_WINDS;
//extern const V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_TYPE_DAMAGING_HAIL;
//extern const V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_TYPE_HURRICANE;
//extern const V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_TYPE_THUNDER_STORM;
//extern const V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_TYPE_TORNADO;
//extern const V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_TYPE_BLIZZARD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_HEAVY_FROST_ON_ROAD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_FUEL_ON_ROAD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_MUD_ON_ROAD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_SNOW_ON_ROAD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_ICE_ON_ROAD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_BLACK_ICE_ON_ROAD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_OIL_ON_ROAD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_LOOSE_CHIPPINGS;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_INSTANT_BLACK_ICE;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_ROADS_SALTED;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_FOG;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_SMOKE;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_HEAVY_SNOW_FALL;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_HEAVY_RAIN;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_HEAVY_HAIL;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_LOW_SUN_GLARE;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_SAND_STORMS;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_SWARMS_OF_INSECTS;
//extern const V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_PRECIPITATION_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_PRECIPITATION_SUB_CAUSE_CODE_TYPE_HEAVY_RAIN;
//extern const V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_PRECIPITATION_SUB_CAUSE_CODE_TYPE_HEAVY_SNOW_FALL;
//extern const V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_PRECIPITATION_SUB_CAUSE_CODE_TYPE_SOFT_HAIL;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_MAINTENANCE_VEHICLE;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_VEHICLES_SLOWING_TO_LOOK_AT_ACCIDENT;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_ABNORMAL_LOAD;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_ABNORMAL_WIDE_LOAD;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_CONVOY;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_SNOW_PLOUGH;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_DEICING;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_SALTING_VEHICLES;
//extern const V2xFac_StationaryVehicleSubCauseCodeType V2xFac_StationaryVehicleSubCauseCodeType_v2XFAC_STATIONARY_VEHICLE_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_StationaryVehicleSubCauseCodeType V2xFac_StationaryVehicleSubCauseCodeType_v2XFAC_STATIONARY_VEHICLE_SUB_CAUSE_CODE_TYPE_HUMAN_PROBLEM;
//extern const V2xFac_StationaryVehicleSubCauseCodeType V2xFac_StationaryVehicleSubCauseCodeType_v2XFAC_STATIONARY_VEHICLE_SUB_CAUSE_CODE_TYPE_VEHICLE_BREAKDOWN;
//extern const V2xFac_StationaryVehicleSubCauseCodeType V2xFac_StationaryVehicleSubCauseCodeType_v2XFAC_STATIONARY_VEHICLE_SUB_CAUSE_CODE_TYPE_POST_CRASH;
//extern const V2xFac_StationaryVehicleSubCauseCodeType V2xFac_StationaryVehicleSubCauseCodeType_v2XFAC_STATIONARY_VEHICLE_SUB_CAUSE_CODE_TYPE_PUBLIC_TRANSPORT_STOP;
//extern const V2xFac_StationaryVehicleSubCauseCodeType V2xFac_StationaryVehicleSubCauseCodeType_v2XFAC_STATIONARY_VEHICLE_SUB_CAUSE_CODE_TYPE_CARRYING_DANGEROUS_GOODS;
//extern const V2xFac_HumanProblemSubCauseCodeType V2xFac_HumanProblemSubCauseCodeType_v2XFAC_HUMAN_PROBLEM_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_HumanProblemSubCauseCodeType V2xFac_HumanProblemSubCauseCodeType_v2XFAC_HUMAN_PROBLEM_SUB_CAUSE_CODE_TYPE_GLYCEMIA_PROBLEM;
//extern const V2xFac_HumanProblemSubCauseCodeType V2xFac_HumanProblemSubCauseCodeType_v2XFAC_HUMAN_PROBLEM_SUB_CAUSE_CODE_TYPE_HEART_PROBLEM;
//extern const V2xFac_EmergencyVehicleApproachingSubCauseCodeType V2xFac_EmergencyVehicleApproachingSubCauseCodeType_v2XFAC_EMERGENCY_VEHICLE_APPROACHING_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_EmergencyVehicleApproachingSubCauseCodeType V2xFac_EmergencyVehicleApproachingSubCauseCodeType_v2XFAC_EMERGENCY_VEHICLE_APPROACHING_SUB_CAUSE_CODE_TYPE_EMERGENCY_VEHICLE_APPROACHING;
//extern const V2xFac_EmergencyVehicleApproachingSubCauseCodeType V2xFac_EmergencyVehicleApproachingSubCauseCodeType_v2XFAC_EMERGENCY_VEHICLE_APPROACHING_SUB_CAUSE_CODE_TYPE_PRIORITIZED_VEHICLE_APPROACHING;
//extern const V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_DANGEROUS_CURVE_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_DANGEROUS_CURVE_SUB_CAUSE_CODE_TYPE_DANGEROUS_LEFT_TURN_CURVE;
//extern const V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_DANGEROUS_CURVE_SUB_CAUSE_CODE_TYPE_DANGEROUS_RIGHT_TURN_CURVE;
//extern const V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_DANGEROUS_CURVE_SUB_CAUSE_CODE_TYPE_MULTIPLE_CURVES_STARTING_WITH_UNKNOWN_TURNING_DIRECTION;
//extern const V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_DANGEROUS_CURVE_SUB_CAUSE_CODE_TYPE_MULTIPLE_CURVES_STARTING_WITH_LEFT_TURN;
//extern const V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_DANGEROUS_CURVE_SUB_CAUSE_CODE_TYPE_MULTIPLE_CURVES_STARTING_WITH_RIGHT_TURN;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_ROCKFALLS;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_EARTHQUAKE_DAMAGE;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_SEWER_COLLAPSE;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_SUBSIDENCE;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_SNOW_DRIFTS;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_STORM_DAMAGE;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_BURST_PIPE;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_VOLCANO_ERUPTION;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_FALLING_ICE;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_SHED_LOAD;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_PARTS_OF_VEHICLES;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_PARTS_OF_TYRES;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_BIG_OBJECTS;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_FALLEN_TREES;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_HUB_CAPS;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_WAITING_VEHICLES;
//extern const V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_ANIMAL_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_ANIMAL_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_WILD_ANIMALS;
//extern const V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_ANIMAL_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_HERD_OF_ANIMALS;
//extern const V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_ANIMAL_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_SMALL_ANIMALS;
//extern const V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_ANIMAL_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_LARGE_ANIMALS;
//extern const V2xFac_CollisionRiskSubCauseCodeType V2xFac_CollisionRiskSubCauseCodeType_v2XFAC_COLLISION_RISK_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_CollisionRiskSubCauseCodeType V2xFac_CollisionRiskSubCauseCodeType_v2XFAC_COLLISION_RISK_SUB_CAUSE_CODE_TYPE_LONGITUDINAL_COLLISION_RISK;
//extern const V2xFac_CollisionRiskSubCauseCodeType V2xFac_CollisionRiskSubCauseCodeType_v2XFAC_COLLISION_RISK_SUB_CAUSE_CODE_TYPE_CROSSING_COLLISION_RISK;
//extern const V2xFac_CollisionRiskSubCauseCodeType V2xFac_CollisionRiskSubCauseCodeType_v2XFAC_COLLISION_RISK_SUB_CAUSE_CODE_TYPE_LATERAL_COLLISION_RISK;
//extern const V2xFac_CollisionRiskSubCauseCodeType V2xFac_CollisionRiskSubCauseCodeType_v2XFAC_COLLISION_RISK_SUB_CAUSE_CODE_TYPE_VULNERABLE_ROAD_USER;
//extern const V2xFac_SignalViolationSubCauseCodeType V2xFac_SignalViolationSubCauseCodeType_v2XFAC_SIGNAL_VIOLATION_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_SignalViolationSubCauseCodeType V2xFac_SignalViolationSubCauseCodeType_v2XFAC_SIGNAL_VIOLATION_SUB_CAUSE_CODE_TYPE_STOP_SIGN_VIOLATION;
//extern const V2xFac_SignalViolationSubCauseCodeType V2xFac_SignalViolationSubCauseCodeType_v2XFAC_SIGNAL_VIOLATION_SUB_CAUSE_CODE_TYPE_TRAFFIC_LIGHT_VIOLATION;
//extern const V2xFac_SignalViolationSubCauseCodeType V2xFac_SignalViolationSubCauseCodeType_v2XFAC_SIGNAL_VIOLATION_SUB_CAUSE_CODE_TYPE_TURNING_REGULATION_VIOLATION;
//extern const V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType_v2XFAC_RESCUE_AND_RECOVERY_WORK_IN_PROGRESS_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType_v2XFAC_RESCUE_AND_RECOVERY_WORK_IN_PROGRESS_SUB_CAUSE_CODE_TYPE_EMERGENCY_VEHICLES;
//extern const V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType_v2XFAC_RESCUE_AND_RECOVERY_WORK_IN_PROGRESS_SUB_CAUSE_CODE_TYPE_RESCUE_HELICOPTER_LANDING;
//extern const V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType_v2XFAC_RESCUE_AND_RECOVERY_WORK_IN_PROGRESS_SUB_CAUSE_CODE_TYPE_POLICE_ACTIVITY_ONGOING;
//extern const V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType_v2XFAC_RESCUE_AND_RECOVERY_WORK_IN_PROGRESS_SUB_CAUSE_CODE_TYPE_MEDICAL_EMERGENCY_ONGOING;
//extern const V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType_v2XFAC_RESCUE_AND_RECOVERY_WORK_IN_PROGRESS_SUB_CAUSE_CODE_TYPE_CHILD_ABDUCTION_IN_PROGRESS;
//extern const V2xFac_DangerousEndOfQueueSubCauseCodeType V2xFac_DangerousEndOfQueueSubCauseCodeType_v2XFAC_DANGEROUS_END_OF_QUEUE_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_DangerousEndOfQueueSubCauseCodeType V2xFac_DangerousEndOfQueueSubCauseCodeType_v2XFAC_DANGEROUS_END_OF_QUEUE_SUB_CAUSE_CODE_TYPE_SUDDEN_END_OF_QUEUE;
//extern const V2xFac_DangerousEndOfQueueSubCauseCodeType V2xFac_DangerousEndOfQueueSubCauseCodeType_v2XFAC_DANGEROUS_END_OF_QUEUE_SUB_CAUSE_CODE_TYPE_QUEUE_OVER_HILL;
//extern const V2xFac_DangerousEndOfQueueSubCauseCodeType V2xFac_DangerousEndOfQueueSubCauseCodeType_v2XFAC_DANGEROUS_END_OF_QUEUE_SUB_CAUSE_CODE_TYPE_QUEUE_AROUND_BEND;
//extern const V2xFac_DangerousEndOfQueueSubCauseCodeType V2xFac_DangerousEndOfQueueSubCauseCodeType_v2XFAC_DANGEROUS_END_OF_QUEUE_SUB_CAUSE_CODE_TYPE_QUEUE_IN_TUNNEL;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_EMERGENCY_ELECTRONIC_BRAKE_ENGAGED;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_PRE_CRASH_SYSTEM_ENGAGED;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_ESP_ENGAGED;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_ABS_ENGAGED;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_AEB_ENGAGED;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_BRAKE_WARNING_ENGAGED;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_COLLISION_RISK_WARNING_ENGAGED;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_LACK_OF_FUEL;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_LACK_OF_BATTERY_POWER;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_ENGINE_PROBLEM;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_TRANSMISSION_PROBLEM;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_ENGINE_COOLING_PROBLEM;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_BRAKING_SYSTEM_PROBLEM;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_STEERING_PROBLEM;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_TYRE_PUNCTURE;
//extern const V2xFac_PostCrashSubCauseCodeType V2xFac_PostCrashSubCauseCodeType_v2XFAC_POST_CRASH_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_PostCrashSubCauseCodeType V2xFac_PostCrashSubCauseCodeType_v2XFAC_POST_CRASH_SUB_CAUSE_CODE_TYPE_ACCIDENT_WITHOUT_E_CALL_TRIGGERED;
//extern const V2xFac_PostCrashSubCauseCodeType V2xFac_PostCrashSubCauseCodeType_v2XFAC_POST_CRASH_SUB_CAUSE_CODE_TYPE_ACCIDENT_WITH_E_CALL_MANUALLY_TRIGGERED;
//extern const V2xFac_PostCrashSubCauseCodeType V2xFac_PostCrashSubCauseCodeType_v2XFAC_POST_CRASH_SUB_CAUSE_CODE_TYPE_ACCIDENT_WITH_E_CALL_AUTOMATICALLY_TRIGGERED;
//extern const V2xFac_PostCrashSubCauseCodeType V2xFac_PostCrashSubCauseCodeType_v2XFAC_POST_CRASH_SUB_CAUSE_CODE_TYPE_ACCIDENT_WITH_E_CALL_TRIGGER_ED_WITHOUT_ACCESS_TO_CELLULAR_NETWORK;
//extern const V2xFac_CurvatureValueType V2xFac_CurvatureValueType_v2XFAC_CURVATURE_VALUE_TYPE_STRAIGHT;
//extern const V2xFac_CurvatureValueType V2xFac_CurvatureValueType_v2XFAC_CURVATURE_VALUE_TYPE_RECIPROCAL_OF_1_METER_RADIUS_TO_RIGHT;
//extern const V2xFac_CurvatureValueType V2xFac_CurvatureValueType_v2XFAC_CURVATURE_VALUE_TYPE_RECIPROCAL_OF_1_METER_RADIUS_TO_LEFT;
//extern const V2xFac_CurvatureValueType V2xFac_CurvatureValueType_v2XFAC_CURVATURE_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_HeadingValueType V2xFac_HeadingValueType_v2XFAC_HEADING_VALUE_TYPE_WGS_84_NORTH;
//extern const V2xFac_HeadingValueType V2xFac_HeadingValueType_v2XFAC_HEADING_VALUE_TYPE_WGS_84_EAST;
//extern const V2xFac_HeadingValueType V2xFac_HeadingValueType_v2XFAC_HEADING_VALUE_TYPE_WGS_84_SOUTH;
//extern const V2xFac_HeadingValueType V2xFac_HeadingValueType_v2XFAC_HEADING_VALUE_TYPE_WGS_84_WEST;
//extern const V2xFac_HeadingValueType V2xFac_HeadingValueType_v2XFAC_HEADING_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_HeadingConfidenceType V2xFac_HeadingConfidenceType_v2XFAC_HEADING_CONFIDENCE_TYPE_EQUAL_OR_WITHIN_ZERO_POINT_ONE_DEGREE;
//extern const V2xFac_HeadingConfidenceType V2xFac_HeadingConfidenceType_v2XFAC_HEADING_CONFIDENCE_TYPE_EQUAL_OR_WITHIN_ONE_DEGREE;
//extern const V2xFac_HeadingConfidenceType V2xFac_HeadingConfidenceType_v2XFAC_HEADING_CONFIDENCE_TYPE_OUT_OF_RANGE;
//extern const V2xFac_HeadingConfidenceType V2xFac_HeadingConfidenceType_v2XFAC_HEADING_CONFIDENCE_TYPE_UNAVAILABLE;
//extern const V2xFac_LanePositionType V2xFac_LanePositionType_v2XFAC_LANE_POSITION_TYPE_OFF_THE_ROAD;
//extern const V2xFac_LanePositionType V2xFac_LanePositionType_v2XFAC_LANE_POSITION_TYPE_HARD_SHOULDER;
//extern const V2xFac_LanePositionType V2xFac_LanePositionType_v2XFAC_LANE_POSITION_TYPE_OUTER_MOST_DRIVING_LANE;
//extern const V2xFac_LanePositionType V2xFac_LanePositionType_v2XFAC_LANE_POSITION_TYPE_SECOND_LANE_FROM_OUTSIDE;
//extern const V2xFac_PerformanceClassType V2xFac_PerformanceClassType_v2XFAC_PERFORMANCE_CLASS_TYPE_UNAVAILABLE;
//extern const V2xFac_PerformanceClassType V2xFac_PerformanceClassType_v2XFAC_PERFORMANCE_CLASS_TYPE_PERFORMANCE_CLASS_A;
//extern const V2xFac_PerformanceClassType V2xFac_PerformanceClassType_v2XFAC_PERFORMANCE_CLASS_TYPE_PERFORMANCE_CLASS_B;
//extern const V2xFac_SpeedValueType V2xFac_SpeedValueType_v2XFAC_SPEED_VALUE_TYPE_STANDSTILL;
//extern const V2xFac_SpeedValueType V2xFac_SpeedValueType_v2XFAC_SPEED_VALUE_TYPE_ONE_CENTIMETER_PER_SEC;
//extern const V2xFac_SpeedValueType V2xFac_SpeedValueType_v2XFAC_SPEED_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_SpeedConfidenceType V2xFac_SpeedConfidenceType_v2XFAC_SPEED_CONFIDENCE_TYPE_EQUAL_OR_WITHIN_ONE_CENTIMETER_PER_SEC;
//extern const V2xFac_SpeedConfidenceType V2xFac_SpeedConfidenceType_v2XFAC_SPEED_CONFIDENCE_TYPE_EQUAL_OR_WITHIN_ONE_METER_PER_SEC;
//extern const V2xFac_SpeedConfidenceType V2xFac_SpeedConfidenceType_v2XFAC_SPEED_CONFIDENCE_TYPE_OUT_OF_RANGE;
//extern const V2xFac_SpeedConfidenceType V2xFac_SpeedConfidenceType_v2XFAC_SPEED_CONFIDENCE_TYPE_UNAVAILABLE;
//extern const V2xFac_VehicleMassType V2xFac_VehicleMassType_v2XFAC_VEHICLE_MASS_TYPE_HUNDRED_KG;
//extern const V2xFac_VehicleMassType V2xFac_VehicleMassType_v2XFAC_VEHICLE_MASS_TYPE_UNAVAILABLE;
//extern const V2xFac_LongitudinalAccelerationValueType V2xFac_LongitudinalAccelerationValueType_v2XFAC_LONGITUDINAL_ACCELERATION_VALUE_TYPE_POINT_ONE_METER_PER_SEC_SQUARED_FORWARD;
//extern const V2xFac_LongitudinalAccelerationValueType V2xFac_LongitudinalAccelerationValueType_v2XFAC_LONGITUDINAL_ACCELERATION_VALUE_TYPE_POINT_ONE_METER_PER_SEC_SQUARED_BACKWARD;
//extern const V2xFac_LongitudinalAccelerationValueType V2xFac_LongitudinalAccelerationValueType_v2XFAC_LONGITUDINAL_ACCELERATION_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_AccelerationConfidenceType V2xFac_AccelerationConfidenceType_v2XFAC_ACCELERATION_CONFIDENCE_TYPE_POINT_ONE_METER_PER_SEC_SQUARED;
//extern const V2xFac_AccelerationConfidenceType V2xFac_AccelerationConfidenceType_v2XFAC_ACCELERATION_CONFIDENCE_TYPE_OUT_OF_RANGE;
//extern const V2xFac_AccelerationConfidenceType V2xFac_AccelerationConfidenceType_v2XFAC_ACCELERATION_CONFIDENCE_TYPE_UNAVAILABLE;
//extern const V2xFac_LateralAccelerationValueType V2xFac_LateralAccelerationValueType_v2XFAC_LATERAL_ACCELERATION_VALUE_TYPE_POINT_ONE_METER_PER_SEC_SQUARED_TO_RIGHT;
//extern const V2xFac_LateralAccelerationValueType V2xFac_LateralAccelerationValueType_v2XFAC_LATERAL_ACCELERATION_VALUE_TYPE_POINT_ONE_METER_PER_SEC_SQUARED_TO_LEFT;
//extern const V2xFac_LateralAccelerationValueType V2xFac_LateralAccelerationValueType_v2XFAC_LATERAL_ACCELERATION_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_VerticalAccelerationValueType V2xFac_VerticalAccelerationValueType_v2XFAC_VERTICAL_ACCELERATION_VALUE_TYPE_POINT_ONE_METER_PER_SEC_SQUARED_UP;
//extern const V2xFac_VerticalAccelerationValueType V2xFac_VerticalAccelerationValueType_v2XFAC_VERTICAL_ACCELERATION_VALUE_TYPE_POINT_ONE_METER_PER_SEC_SQUARED_DOWN;
//extern const V2xFac_VerticalAccelerationValueType V2xFac_VerticalAccelerationValueType_v2XFAC_VERTICAL_ACCELERATION_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_UNKNOWN;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_PEDESTRIAN;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_CYCLIST;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_MOPED;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_MOTORCYCLE;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_PASSENGERCAR;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_BUS;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_LIGHTTRUCK;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_HEAVYTRUCK;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_TRAILER;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_SPECIALVEHICLES;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_TRAM;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_ROADSIDEUNIT;
//extern const V2xFac_HeightLonCarrType V2xFac_HeightLonCarrType_v2XFAC_HEIGHT_LON_CAR_R_TYPE_ONE_CENTIMETER;
//extern const V2xFac_HeightLonCarrType V2xFac_HeightLonCarrType_v2XFAC_HEIGHT_LON_CAR_R_TYPE_UNAVAILABLE;
//extern const V2xFac_PosLonCarrType V2xFac_PosLonCarrType_v2XFAC_POS_LON_CAR_R_TYPE_ONE_CENTIMETER;
//extern const V2xFac_PosLonCarrType V2xFac_PosLonCarrType_v2XFAC_POS_LON_CAR_R_TYPE_UNAVAILABLE;
//extern const V2xFac_PosPillarType V2xFac_PosPillarType_v2XFAC_POS_PILLAR_TYPE_TEN_CENTIMETERS;
//extern const V2xFac_PosPillarType V2xFac_PosPillarType_v2XFAC_POS_PILLAR_TYPE_UNAVAILABLE;
//extern const V2xFac_PosCentMassType V2xFac_PosCentMassType_v2XFAC_POS_CENT_MASS_TYPE_TEN_CENTIMETERS;
//extern const V2xFac_PosCentMassType V2xFac_PosCentMassType_v2XFAC_POS_CENT_MASS_TYPE_UNAVAILABLE;
//extern const V2xFac_SpeedLimitType V2xFac_SpeedLimitType_v2XFAC_SPEED_LIMIT_TYPE_ONE_KM_PER_HOUR;
//extern const V2xFac_TemperatureType V2xFac_TemperatureType_v2XFAC_TEMPERATURE_TYPE_EQUAL_OR_SMALLER_THAN_MINUS_60DEG;
//extern const V2xFac_TemperatureType V2xFac_TemperatureType_v2XFAC_TEMPERATURE_TYPE_ONE_DEGREE_CELSIUS;
//extern const V2xFac_TemperatureType V2xFac_TemperatureType_v2XFAC_TEMPERATURE_TYPE_EQUAL_OR_GREATER_THAN_67DEG;
//extern const V2xFac_WheelBaseVehicleType V2xFac_WheelBaseVehicleType_v2XFAC_WHEEL_BASE_VEHICLE_TYPE_TEN_CENTIMETERS;
//extern const V2xFac_WheelBaseVehicleType V2xFac_WheelBaseVehicleType_v2XFAC_WHEEL_BASE_VEHICLE_TYPE_UNAVAILABLE;
//extern const V2xFac_TurningRadiusType V2xFac_TurningRadiusType_v2XFAC_TURNING_RADIUS_TYPE_POINT_4_METERS;
//extern const V2xFac_TurningRadiusType V2xFac_TurningRadiusType_v2XFAC_TURNING_RADIUS_TYPE_UNAVAILABLE;
//extern const V2xFac_PosFrontAxType V2xFac_PosFrontAxType_v2XFAC_POS_FRONT_AX_TYPE_TEN_CENTIMETERS;
//extern const V2xFac_PosFrontAxType V2xFac_PosFrontAxType_v2XFAC_POS_FRONT_AX_TYPE_UNAVAILABLE;
//extern const V2xFac_VehicleLengthValueType V2xFac_VehicleLengthValueType_v2XFAC_VEHICLE_LENGTH_VALUE_TYPE_TEN_CENTIMETERS;
//extern const V2xFac_VehicleLengthValueType V2xFac_VehicleLengthValueType_v2XFAC_VEHICLE_LENGTH_VALUE_TYPE_OUT_OF_RANGE;
//extern const V2xFac_VehicleLengthValueType V2xFac_VehicleLengthValueType_v2XFAC_VEHICLE_LENGTH_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_VehicleWidthType V2xFac_VehicleWidthType_v2XFAC_VEHICLE_WIDTH_TYPE_TEN_CENTIMETERS;
//extern const V2xFac_VehicleWidthType V2xFac_VehicleWidthType_v2XFAC_VEHICLE_WIDTH_TYPE_OUT_OF_RANGE;
//extern const V2xFac_VehicleWidthType V2xFac_VehicleWidthType_v2XFAC_VEHICLE_WIDTH_TYPE_UNAVAILABLE;
//extern const V2xFac_InformationQualityType V2xFac_InformationQualityType_v2XFAC_INFORMATION_QUALITY_TYPE_UNAVAILABLE;
//extern const V2xFac_InformationQualityType V2xFac_InformationQualityType_v2XFAC_INFORMATION_QUALITY_TYPE_LOWEST;
//extern const V2xFac_InformationQualityType V2xFac_InformationQualityType_v2XFAC_INFORMATION_QUALITY_TYPE_HIGHEST;
//extern const V2xFac_SteeringWheelAngleValueType V2xFac_SteeringWheelAngleValueType_v2XFAC_STEERING_WHEEL_ANGLE_VALUE_TYPE_STRAIGHT;
//extern const V2xFac_SteeringWheelAngleValueType V2xFac_SteeringWheelAngleValueType_v2XFAC_STEERING_WHEEL_ANGLE_VALUE_TYPE_ONE_POINT_FIVE_DEGREES_TO_RIGHT;
//extern const V2xFac_SteeringWheelAngleValueType V2xFac_SteeringWheelAngleValueType_v2XFAC_STEERING_WHEEL_ANGLE_VALUE_TYPE_ONE_POINT_FIVE_DEGREES_TO_LEFT;
//extern const V2xFac_SteeringWheelAngleValueType V2xFac_SteeringWheelAngleValueType_v2XFAC_STEERING_WHEEL_ANGLE_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_SteeringWheelAngleConfidenceType V2xFac_SteeringWheelAngleConfidenceType_v2XFAC_STEERING_WHEEL_ANGLE_CONFIDENCE_TYPE_EQUAL_OR_WITH_IN_ONE_POINT_FIVE_DEGREE;
//extern const V2xFac_SteeringWheelAngleConfidenceType V2xFac_SteeringWheelAngleConfidenceType_v2XFAC_STEERING_WHEEL_ANGLE_CONFIDENCE_TYPE_OUT_OF_RANGE;
//extern const V2xFac_SteeringWheelAngleConfidenceType V2xFac_SteeringWheelAngleConfidenceType_v2XFAC_STEERING_WHEEL_ANGLE_CONFIDENCE_TYPE_UNAVAILABLE;
//extern const V2xFac_TimestampItsType V2xFac_TimestampItsType_v2XFAC_TIME_STAMP_ITS_TYPE_UTC_START_OF_2004;
//extern const V2xFac_TimestampItsType V2xFac_TimestampItsType_v2XFAC_TIME_STAMP_ITS_TYPE_ONE_MILLI_SEC_AFTER_UTC_START_OF_2004;
//extern const V2xFac_YawRateValueType V2xFac_YawRateValueType_v2XFAC_YAWRATE_VALUE_TYPE_STRAIGHT;
//extern const V2xFac_YawRateValueType V2xFac_YawRateValueType_v2XFAC_YAWRATE_VALUE_TYPE_DEGSEC_000_01_TO_RIGHT;
//extern const V2xFac_YawRateValueType V2xFac_YawRateValueType_v2XFAC_YAWRATE_VALUE_TYPE_DEGSEC_000_01_TO_LEFT;
//extern const V2xFac_YawRateValueType V2xFac_YawRateValueType_v2XFAC_YAWRATE_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_TransmissionIntervalType V2xFac_TransmissionIntervalType_v2XFAC_TRANSMISSION_INTERVAL_TYPE_one_Milli_Second;
//extern const V2xFac_TransmissionIntervalType V2xFac_TransmissionIntervalType_v2XFAC_TRANSMISSION_INTERVAL_TYPE_ten_Seconds;
//extern const V2xFac_ValidityDurationType V2xFac_ValidityDurationType_v2XFAC_VALIDITY_DURATION_TYPE_TIME_OF_DETECTION;
//extern const V2xFac_ValidityDurationType V2xFac_ValidityDurationType_v2XFAC_VALIDITY_DURATION_TYPE_ONE_SECOND_AFTER_DETECTION;
//extern const V2xFac_NumberOfOccupantsType V2xFac_NumberOfOccupantsType_v2XFAC_NUMBER_OF_OCCUPANTS_TYPE_ONE_OCCUPANT;
//extern const V2xFac_NumberOfOccupantsType V2xFac_NumberOfOccupantsType_v2XFAC_NUMBER_OF_OCCUPANTS_TYPE_UNAVAILABLE;
//extern const V2xFac_ProtectedZoneRadiusType V2xFac_ProtectedZoneRadiusType_v2XFAC_PROTECTED_ZONE_RADIUS_TYPE_ONE_METER;
//extern const V2xFac_GenerationDeltaTime V2xFac_GenerationDeltaTime_v2XFAC_GENERATION_DELTA_TIME_ONE_MILLI_SEC;

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif
