#ifndef GENERATED_ASN1SCC_DENM_H
#define GENERATED_ASN1SCC_DENM_H
/*
	Code automatically generated by asn1scc tool.
	Edited by Sayed Badr:
	1- Commenting all externed variables.
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"
#include "ITS.h"


#ifdef  __cplusplus
extern "C" {
#endif


/*-- V2xFac_ImpactReductionContainerType --------------------------------------------*/
typedef struct {
    V2xFac_HeightLonCarrType heightLonCarrLeft;
    V2xFac_HeightLonCarrType heightLonCarrRight;
    V2xFac_PosLonCarrType posLonCarrLeft;
    V2xFac_PosLonCarrType posLonCarrRight;
    V2xFac_PositionOfPillarsType positionOfPillars;
    V2xFac_PosCentMassType posCentMass;
    V2xFac_WheelBaseVehicleType wheelBaseVehicle;
    V2xFac_TurningRadiusType turningRadius;
    V2xFac_PosFrontAxType posFrontAx;
    V2xFac_PositionOfOccupantsType positionOfOccupants;
    V2xFac_VehicleMassType vehicleMass;
    V2xFac_RequestResponseIndicationType requestResponseIndication;

} V2xFac_ImpactReductionContainerType;

void V2xFac_ImpactReductionContainerType_Initialize(V2xFac_ImpactReductionContainerType* pVal);

#define ERR_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE		6791  /**/
#define ERR_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_HEIGHTLONCARRLEFT_2		6616  /**/
#define ERR_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_HEIGHTLONCARRRIGHT_2		6630  /**/
#define ERR_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSLONCARRLEFT_2		6644  /**/
#define ERR_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSLONCARRRIGHT_2		6658  /**/
#define ERR_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSITIONOFPILLARS_2		6686  /**/
#define ERR_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSCENTMASS_2		6700  /**/
#define ERR_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_WHEELBASEVEHICLE_2		6714  /**/
#define ERR_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_TURNINGRADIUS_2		6728  /**/
#define ERR_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSFRONTAX_2		6742  /**/
#define ERR_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSITIONOFOCCUPANTS_2		6756  /**/
#define ERR_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_VEHICLEMASS_2		6770  /**/
#define ERR_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_REQUESTRESPONSEINDICATION_2		6784  /**/
flag V2xFac_ImpactReductionContainerType_IsConstraintValid(const V2xFac_ImpactReductionContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE		6792  /**/
#define ERR_UPER_ENCODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_HEIGHTLONCARRLEFT_2		6617  /**/
#define ERR_UPER_ENCODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_HEIGHTLONCARRRIGHT_2		6631  /**/
#define ERR_UPER_ENCODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSLONCARRLEFT_2		6645  /**/
#define ERR_UPER_ENCODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSLONCARRRIGHT_2		6659  /**/
#define ERR_UPER_ENCODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSITIONOFPILLARS_2		6687  /**/
#define ERR_UPER_ENCODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSCENTMASS_2		6701  /**/
#define ERR_UPER_ENCODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_WHEELBASEVEHICLE_2		6715  /**/
#define ERR_UPER_ENCODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_TURNINGRADIUS_2		6729  /**/
#define ERR_UPER_ENCODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSFRONTAX_2		6743  /**/
#define ERR_UPER_ENCODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSITIONOFOCCUPANTS_2		6757  /**/
#define ERR_UPER_ENCODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_VEHICLEMASS_2		6771  /**/
#define ERR_UPER_ENCODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_REQUESTRESPONSEINDICATION_2		6785  /**/
#define V2xFac_ImpactReductionContainerType_REQUIRED_BYTES_FOR_ENCODING       13
#define V2xFac_ImpactReductionContainerType_REQUIRED_BITS_FOR_ENCODING        102

flag V2xFac_ImpactReductionContainerType_Encode(const V2xFac_ImpactReductionContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE		6793  /**/
#define ERR_UPER_DECODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_HEIGHTLONCARRLEFT_2		6618  /**/
#define ERR_UPER_DECODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_HEIGHTLONCARRRIGHT_2		6632  /**/
#define ERR_UPER_DECODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSLONCARRLEFT_2		6646  /**/
#define ERR_UPER_DECODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSLONCARRRIGHT_2		6660  /**/
#define ERR_UPER_DECODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSITIONOFPILLARS_2		6688  /**/
#define ERR_UPER_DECODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSCENTMASS_2		6702  /**/
#define ERR_UPER_DECODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_WHEELBASEVEHICLE_2		6716  /**/
#define ERR_UPER_DECODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_TURNINGRADIUS_2		6730  /**/
#define ERR_UPER_DECODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSFRONTAX_2		6744  /**/
#define ERR_UPER_DECODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_POSITIONOFOCCUPANTS_2		6758  /**/
#define ERR_UPER_DECODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_VEHICLEMASS_2		6772  /**/
#define ERR_UPER_DECODE_V2XFAC_IMPACTREDUCTIONCONTAINERTYPE_REQUESTRESPONSEINDICATION_2		6786  /**/
flag V2xFac_ImpactReductionContainerType_Decode(V2xFac_ImpactReductionContainerType* pVal, BitStream* pBitStrm, int* pErrCode);


/*-- V2xFac_SituationContainerType --------------------------------------------*/
typedef struct {
    V2xFac_InformationQualityType informationQuality;
    V2xFac_CauseCodeType eventType;
    V2xFac_CauseCodeType linkedCause;
    V2xFac_EventHistoryType eventHistory;

    struct {
        unsigned int linkedCause:1;
        unsigned int eventHistory:1;
    } exist;

} V2xFac_SituationContainerType;

void V2xFac_SituationContainerType_Initialize(V2xFac_SituationContainerType* pVal);

#define ERR_V2XFAC_SITUATIONCONTAINERTYPE		6385  /**/
#define ERR_V2XFAC_SITUATIONCONTAINERTYPE_INFORMATIONQUALITY_2		6182  /**/
#define ERR_V2XFAC_SITUATIONCONTAINERTYPE_EVENTTYPE_2		6224  /**/
#define ERR_V2XFAC_SITUATIONCONTAINERTYPE_LINKEDCAUSE_2		6266  /**/
#define ERR_V2XFAC_SITUATIONCONTAINERTYPE_EVENTHISTORY_2		6378  /**/
flag V2xFac_SituationContainerType_IsConstraintValid(const V2xFac_SituationContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_SITUATIONCONTAINERTYPE		6386  /**/
#define ERR_UPER_ENCODE_V2XFAC_SITUATIONCONTAINERTYPE_INFORMATIONQUALITY_2		6183  /**/
#define ERR_UPER_ENCODE_V2XFAC_SITUATIONCONTAINERTYPE_EVENTTYPE_2		6225  /**/
#define ERR_UPER_ENCODE_V2XFAC_SITUATIONCONTAINERTYPE_LINKEDCAUSE_2		6267  /**/
#define ERR_UPER_ENCODE_V2XFAC_SITUATIONCONTAINERTYPE_EVENTHISTORY_2		6379  /**/
#define V2xFac_SituationContainerType_REQUIRED_BYTES_FOR_ENCODING       210
#define V2xFac_SituationContainerType_REQUIRED_BITS_FOR_ENCODING        1675

flag V2xFac_SituationContainerType_Encode(const V2xFac_SituationContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_SITUATIONCONTAINERTYPE		6387  /**/
#define ERR_UPER_DECODE_V2XFAC_SITUATIONCONTAINERTYPE_INFORMATIONQUALITY_2		6184  /**/
#define ERR_UPER_DECODE_V2XFAC_SITUATIONCONTAINERTYPE_EVENTTYPE_2		6226  /**/
#define ERR_UPER_DECODE_V2XFAC_SITUATIONCONTAINERTYPE_LINKEDCAUSE_2		6268  /**/
#define ERR_UPER_DECODE_V2XFAC_SITUATIONCONTAINERTYPE_EVENTHISTORY_2		6380  /**/
flag V2xFac_SituationContainerType_Decode(V2xFac_SituationContainerType* pVal, BitStream* pBitStrm, int* pErrCode);

/*-- V2xFac_LocationContainerType --------------------------------------------*/
typedef struct {
    V2xFac_SpeedType eventSpeed;
    V2xFac_HeadingType eventPositionHeading;
    V2xFac_TracesType traces;
    V2xFac_RoadTypeType roadType;

    struct {
        unsigned int eventSpeed:1;
        unsigned int eventPositionHeading:1;
        unsigned int roadType:1;
    } exist;

} V2xFac_LocationContainerType;

void V2xFac_LocationContainerType_Initialize(V2xFac_LocationContainerType* pVal);

#define ERR_V2XFAC_LOCATIONCONTAINERTYPE		6602  /**/
#define ERR_V2XFAC_LOCATIONCONTAINERTYPE_EVENTSPEED_2		6427  /**/
#define ERR_V2XFAC_LOCATIONCONTAINERTYPE_EVENTPOSITIONHEADING_2		6469  /**/
#define ERR_V2XFAC_LOCATIONCONTAINERTYPE_TRACES_2		6581  /**/
#define ERR_V2XFAC_LOCATIONCONTAINERTYPE_ROADTYPE_2		6595  /**/
flag V2xFac_LocationContainerType_IsConstraintValid(const V2xFac_LocationContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_LOCATIONCONTAINERTYPE		6603  /**/
#define ERR_UPER_ENCODE_V2XFAC_LOCATIONCONTAINERTYPE_EVENTSPEED_2		6428  /**/
#define ERR_UPER_ENCODE_V2XFAC_LOCATIONCONTAINERTYPE_EVENTPOSITIONHEADING_2		6470  /**/
#define ERR_UPER_ENCODE_V2XFAC_LOCATIONCONTAINERTYPE_TRACES_2		6582  /**/
#define ERR_UPER_ENCODE_V2XFAC_LOCATIONCONTAINERTYPE_ROADTYPE_2		6596  /**/
#define V2xFac_LocationContainerType_REQUIRED_BYTES_FOR_ENCODING       2392
#define V2xFac_LocationContainerType_REQUIRED_BITS_FOR_ENCODING        19130

flag V2xFac_LocationContainerType_Encode(const V2xFac_LocationContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_LOCATIONCONTAINERTYPE		6604  /**/
#define ERR_UPER_DECODE_V2XFAC_LOCATIONCONTAINERTYPE_EVENTSPEED_2		6429  /**/
#define ERR_UPER_DECODE_V2XFAC_LOCATIONCONTAINERTYPE_EVENTPOSITIONHEADING_2		6471  /**/
#define ERR_UPER_DECODE_V2XFAC_LOCATIONCONTAINERTYPE_TRACES_2		6583  /**/
#define ERR_UPER_DECODE_V2XFAC_LOCATIONCONTAINERTYPE_ROADTYPE_2		6597  /**/
flag V2xFac_LocationContainerType_Decode(V2xFac_LocationContainerType* pVal, BitStream* pBitStrm, int* pErrCode);

/*-- V2xFac_StationaryVehicleContainerType --------------------------------------------*/
typedef struct {
    V2xFac_StationarySinceType stationarySince;
    V2xFac_CauseCodeType stationaryCause;
    V2xFac_DangerousGoodsExtendedType carryingDangerousGoods;
    V2xFac_NumberOfOccupantsType numberOfOccupants;
    V2xFac_VehicleIdentificationType vehicleIdentification;
    V2xFac_EnergyStorageTypeType energyStorageType;

    struct {
        unsigned int stationarySince:1;
        unsigned int stationaryCause:1;
        unsigned int carryingDangerousGoods:1;
        unsigned int numberOfOccupants:1;
        unsigned int vehicleIdentification:1;
        unsigned int energyStorageType:1;
    } exist;

} V2xFac_StationaryVehicleContainerType;

void V2xFac_StationaryVehicleContainerType_Initialize(V2xFac_StationaryVehicleContainerType* pVal);

#define ERR_V2XFAC_STATIONARYVEHICLECONTAINERTYPE		7428  /**/
#define ERR_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_STATIONARYSINCE_2		7232  /**/
#define ERR_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_STATIONARYCAUSE_2		7274  /**/
#define ERR_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_CARRYINGDANGEROUSGOODS_2		7351  /**/
#define ERR_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_NUMBEROFOCCUPANTS_2		7365  /**/
#define ERR_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_VEHICLEIDENTIFICATION_2		7407  /**/
#define ERR_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_ENERGYSTORAGETYPE_2		7421  /**/
flag V2xFac_StationaryVehicleContainerType_IsConstraintValid(const V2xFac_StationaryVehicleContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_STATIONARYVEHICLECONTAINERTYPE		7429  /**/
#define ERR_UPER_ENCODE_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_STATIONARYSINCE_2		7233  /**/
#define ERR_UPER_ENCODE_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_STATIONARYCAUSE_2		7275  /**/
#define ERR_UPER_ENCODE_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_CARRYINGDANGEROUSGOODS_2		7352  /**/
#define ERR_UPER_ENCODE_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_NUMBEROFOCCUPANTS_2		7366  /**/
#define ERR_UPER_ENCODE_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_VEHICLEIDENTIFICATION_2		7408  /**/
#define ERR_UPER_ENCODE_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_ENERGYSTORAGETYPE_2		7422  /**/
#define V2xFac_StationaryVehicleContainerType_REQUIRED_BYTES_FOR_ENCODING       82
#define V2xFac_StationaryVehicleContainerType_REQUIRED_BITS_FOR_ENCODING        649

flag V2xFac_StationaryVehicleContainerType_Encode(const V2xFac_StationaryVehicleContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_STATIONARYVEHICLECONTAINERTYPE		7430  /**/
#define ERR_UPER_DECODE_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_STATIONARYSINCE_2		7234  /**/
#define ERR_UPER_DECODE_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_STATIONARYCAUSE_2		7276  /**/
#define ERR_UPER_DECODE_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_CARRYINGDANGEROUSGOODS_2		7353  /**/
#define ERR_UPER_DECODE_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_NUMBEROFOCCUPANTS_2		7367  /**/
#define ERR_UPER_DECODE_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_VEHICLEIDENTIFICATION_2		7409  /**/
#define ERR_UPER_DECODE_V2XFAC_STATIONARYVEHICLECONTAINERTYPE_ENERGYSTORAGETYPE_2		7423  /**/
flag V2xFac_StationaryVehicleContainerType_Decode(V2xFac_StationaryVehicleContainerType* pVal, BitStream* pBitStrm, int* pErrCode);

typedef struct {
    int nCount;

    V2xFac_ActionIdType arr[8];
} V2xFac_ReferenceDenmsType;

void V2xFac_ReferenceDenmsType_Initialize(V2xFac_ReferenceDenmsType* pVal);

#define ERR_V2XFAC_REFERENCEDENMSTYPE		8380  /**/
#define ERR_V2XFAC_REFERENCEDENMSTYPE_ELM_2		8373  /**/
flag V2xFac_ReferenceDenmsType_IsConstraintValid(const V2xFac_ReferenceDenmsType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_REFERENCEDENMSTYPE		8381  /**/
#define ERR_UPER_ENCODE_V2XFAC_REFERENCEDENMSTYPE_ELM_2		8374  /**/
#define V2xFac_ReferenceDenmsType_REQUIRED_BYTES_FOR_ENCODING       49
#define V2xFac_ReferenceDenmsType_REQUIRED_BITS_FOR_ENCODING        387

flag V2xFac_ReferenceDenmsType_Encode(const V2xFac_ReferenceDenmsType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_REFERENCEDENMSTYPE		8382  /**/
#define ERR_UPER_DECODE_V2XFAC_REFERENCEDENMSTYPE_ELM_2		8375  /**/
flag V2xFac_ReferenceDenmsType_Decode(V2xFac_ReferenceDenmsType* pVal, BitStream* pBitStrm, int* pErrCode);

/*-- V2xFac_RoadWorksContainerExtendedType --------------------------------------------*/
typedef struct {
    V2xFac_LightBarSirenInUseType lightBarSirenInUse;
    V2xFac_ClosedLanesType closedLanes;
    V2xFac_RestrictedTypesType restriction;
    V2xFac_SpeedLimitType speedLimit;
    V2xFac_CauseCodeType incidentIndication;
    V2xFac_ItineraryPathType recommendedPath;
    V2xFac_DeltaReferencePositionType startingPointSpeedLimit;
    V2xFac_TrafficRuleType trafficFlowRule;
    V2xFac_ReferenceDenmsType referenceDenms;

    struct {
        unsigned int lightBarSirenInUse:1;
        unsigned int closedLanes:1;
        unsigned int restriction:1;
        unsigned int speedLimit:1;
        unsigned int incidentIndication:1;
        unsigned int recommendedPath:1;
        unsigned int startingPointSpeedLimit:1;
        unsigned int trafficFlowRule:1;
        unsigned int referenceDenms:1;
    } exist;

} V2xFac_RoadWorksContainerExtendedType;

void V2xFac_RoadWorksContainerExtendedType_Initialize(V2xFac_RoadWorksContainerExtendedType* pVal);

#define ERR_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE		7218  /**/
#define ERR_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_LIGHTBARSIRENINUSE_2		6805  /**/
#define ERR_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_CLOSEDLANES_2		6847  /**/
#define ERR_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_RESTRICTION_2		6875  /**/
#define ERR_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_SPEEDLIMIT_2		6889  /**/
#define ERR_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_INCIDENTINDICATION_2		6931  /**/
#define ERR_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_RECOMMENDEDPATH_2		7085  /**/
#define ERR_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_STARTINGPOINTSPEEDLIMIT_2		7141  /**/
#define ERR_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_TRAFFICFLOWRULE_2		7155  /**/
#define ERR_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_REFERENCEDENMS_2		7211  /**/
flag V2xFac_RoadWorksContainerExtendedType_IsConstraintValid(const V2xFac_RoadWorksContainerExtendedType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE		7219  /**/
#define ERR_UPER_ENCODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_LIGHTBARSIRENINUSE_2		6806  /**/
#define ERR_UPER_ENCODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_CLOSEDLANES_2		6848  /**/
#define ERR_UPER_ENCODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_RESTRICTION_2		6876  /**/
#define ERR_UPER_ENCODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_SPEEDLIMIT_2		6890  /**/
#define ERR_UPER_ENCODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_INCIDENTINDICATION_2		6932  /**/
#define ERR_UPER_ENCODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_RECOMMENDEDPATH_2		7086  /**/
#define ERR_UPER_ENCODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_STARTINGPOINTSPEEDLIMIT_2		7142  /**/
#define ERR_UPER_ENCODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_TRAFFICFLOWRULE_2		7156  /**/
#define ERR_UPER_ENCODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_REFERENCEDENMS_2		7212  /**/
#define V2xFac_RoadWorksContainerExtendedType_REQUIRED_BYTES_FOR_ENCODING       681
#define V2xFac_RoadWorksContainerExtendedType_REQUIRED_BITS_FOR_ENCODING        5448

flag V2xFac_RoadWorksContainerExtendedType_Encode(const V2xFac_RoadWorksContainerExtendedType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE		7220  /**/
#define ERR_UPER_DECODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_LIGHTBARSIRENINUSE_2		6807  /**/
#define ERR_UPER_DECODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_CLOSEDLANES_2		6849  /**/
#define ERR_UPER_DECODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_RESTRICTION_2		6877  /**/
#define ERR_UPER_DECODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_SPEEDLIMIT_2		6891  /**/
#define ERR_UPER_DECODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_INCIDENTINDICATION_2		6933  /**/
#define ERR_UPER_DECODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_RECOMMENDEDPATH_2		7087  /**/
#define ERR_UPER_DECODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_STARTINGPOINTSPEEDLIMIT_2		7143  /**/
#define ERR_UPER_DECODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_TRAFFICFLOWRULE_2		7157  /**/
#define ERR_UPER_DECODE_V2XFAC_ROADWORKSCONTAINEREXTENDEDTYPE_REFERENCEDENMS_2		7213  /**/
flag V2xFac_RoadWorksContainerExtendedType_Decode(V2xFac_RoadWorksContainerExtendedType* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- V2xFac_AlacarteContainerType --------------------------------------------*/
typedef struct {
    V2xFac_LanePositionType lanePosition;
    V2xFac_ImpactReductionContainerType impactReduction;
    V2xFac_TemperatureType externalTemperature;
    V2xFac_RoadWorksContainerExtendedType roadWorks;
    V2xFac_PositioningSolutionTypeType positioningSolution;
    V2xFac_StationaryVehicleContainerType stationaryVehicle;

    struct {
        unsigned int lanePosition:1;
        unsigned int impactReduction:1;
        unsigned int externalTemperature:1;
        unsigned int roadWorks:1;
        unsigned int positioningSolution:1;
        unsigned int stationaryVehicle:1;
    } exist;

} V2xFac_AlacarteContainerType;

void V2xFac_AlacarteContainerType_Initialize(V2xFac_AlacarteContainerType* pVal);

#define ERR_V2XFAC_ALACARTECONTAINERTYPE		8324  /**/
#define ERR_V2XFAC_ALACARTECONTAINERTYPE_LANEPOSITION_2		7442  /**/
#define ERR_V2XFAC_ALACARTECONTAINERTYPE_IMPACTREDUCTION_2		7638  /**/
#define ERR_V2XFAC_ALACARTECONTAINERTYPE_EXTERNALTEMPERATURE_2		7652  /**/
#define ERR_V2XFAC_ALACARTECONTAINERTYPE_ROADWORKS_2		8086  /**/
#define ERR_V2XFAC_ALACARTECONTAINERTYPE_POSITIONINGSOLUTION_2		8100  /**/
#define ERR_V2XFAC_ALACARTECONTAINERTYPE_STATIONARYVEHICLE_2		8317  /**/
flag V2xFac_AlacarteContainerType_IsConstraintValid(const V2xFac_AlacarteContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_ALACARTECONTAINERTYPE		8325  /**/
#define ERR_UPER_ENCODE_V2XFAC_ALACARTECONTAINERTYPE_LANEPOSITION_2		7443  /**/
#define ERR_UPER_ENCODE_V2XFAC_ALACARTECONTAINERTYPE_IMPACTREDUCTION_2		7639  /**/
#define ERR_UPER_ENCODE_V2XFAC_ALACARTECONTAINERTYPE_EXTERNALTEMPERATURE_2		7653  /**/
#define ERR_UPER_ENCODE_V2XFAC_ALACARTECONTAINERTYPE_ROADWORKS_2		8087  /**/
#define ERR_UPER_ENCODE_V2XFAC_ALACARTECONTAINERTYPE_POSITIONINGSOLUTION_2		8101  /**/
#define ERR_UPER_ENCODE_V2XFAC_ALACARTECONTAINERTYPE_STATIONARYVEHICLE_2		8318  /**/
#define V2xFac_AlacarteContainerType_REQUIRED_BYTES_FOR_ENCODING       778
#define V2xFac_AlacarteContainerType_REQUIRED_BITS_FOR_ENCODING        6219

flag V2xFac_AlacarteContainerType_Encode(const V2xFac_AlacarteContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_ALACARTECONTAINERTYPE		8326  /**/
#define ERR_UPER_DECODE_V2XFAC_ALACARTECONTAINERTYPE_LANEPOSITION_2		7444  /**/
#define ERR_UPER_DECODE_V2XFAC_ALACARTECONTAINERTYPE_IMPACTREDUCTION_2		7640  /**/
#define ERR_UPER_DECODE_V2XFAC_ALACARTECONTAINERTYPE_EXTERNALTEMPERATURE_2		7654  /**/
#define ERR_UPER_DECODE_V2XFAC_ALACARTECONTAINERTYPE_ROADWORKS_2		8088  /**/
#define ERR_UPER_DECODE_V2XFAC_ALACARTECONTAINERTYPE_POSITIONINGSOLUTION_2		8102  /**/
#define ERR_UPER_DECODE_V2XFAC_ALACARTECONTAINERTYPE_STATIONARYVEHICLE_2		8319  /**/
flag V2xFac_AlacarteContainerType_Decode(V2xFac_AlacarteContainerType* pVal, BitStream* pBitStrm, int* pErrCode);

typedef enum {
    v2XFAC_TERMINATION_TYPE_IS_CANCELLATION = 0,
    v2XFAC_TERMINATION_TYPE_IS_NEGATION = 1
} V2xFac_TerminationType;

// please use the following macros to avoid breaking code.
#define V2xFac_TerminationType_v2XFAC_TERMINATION_TYPE_IS_CANCELLATION v2XFAC_TERMINATION_TYPE_IS_CANCELLATION
#define V2xFac_TerminationType_v2XFAC_TERMINATION_TYPE_IS_NEGATION v2XFAC_TERMINATION_TYPE_IS_NEGATION

void V2xFac_TerminationType_Initialize(V2xFac_TerminationType* pVal);

#define ERR_V2XFAC_TERMINATIONTYPE		8331  /**/
flag V2xFac_TerminationType_IsConstraintValid(const V2xFac_TerminationType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_TERMINATIONTYPE		8332  /**/
#define V2xFac_TerminationType_REQUIRED_BYTES_FOR_ENCODING       1 
#define V2xFac_TerminationType_REQUIRED_BITS_FOR_ENCODING        1

flag V2xFac_TerminationType_Encode(const V2xFac_TerminationType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_TERMINATIONTYPE		8333  /**/
flag V2xFac_TerminationType_Decode(V2xFac_TerminationType* pVal, BitStream* pBitStrm, int* pErrCode);

/*-- V2xFac_ManagementContainerType --------------------------------------------*/
typedef struct {
    V2xFac_ActionIdType actionID;
    V2xFac_TimestampItsType detectionTime;
    V2xFac_TimestampItsType referenceTime;
    V2xFac_TerminationType termination;
    V2xFac_ReferencePositionType eventPosition;
    V2xFac_RelevanceDistanceType relevanceDistance;
    V2xFac_RelevanceTrafficDirectionType relevanceTrafficDirection;
    V2xFac_ValidityDurationType validityDuration;
    V2xFac_TransmissionIntervalType transmissionInterval;
    V2xFac_StationTypeType stationType;

    struct {
        unsigned int termination:1;
        unsigned int relevanceDistance:1;
        unsigned int relevanceTrafficDirection:1;
        unsigned int validityDuration:1;
        unsigned int transmissionInterval:1;
    } exist;

} V2xFac_ManagementContainerType;

void V2xFac_ManagementContainerType_Initialize(V2xFac_ManagementContainerType* pVal);

#define ERR_V2XFAC_MANAGEMENTCONTAINERTYPE		6168  /**/
#define ERR_V2XFAC_MANAGEMENTCONTAINERTYPE_ACTIONID_2		5909  /**/
#define ERR_V2XFAC_MANAGEMENTCONTAINERTYPE_DETECTIONTIME_2		5923  /**/
#define ERR_V2XFAC_MANAGEMENTCONTAINERTYPE_REFERENCETIME_2		5937  /**/
#define ERR_V2XFAC_MANAGEMENTCONTAINERTYPE_TERMINATION_2		5951  /**/
#define ERR_V2XFAC_MANAGEMENTCONTAINERTYPE_EVENTPOSITION_2		6091  /**/
#define ERR_V2XFAC_MANAGEMENTCONTAINERTYPE_RELEVANCEDISTANCE_2		6105  /**/
#define ERR_V2XFAC_MANAGEMENTCONTAINERTYPE_RELEVANCETRAFFICDIRECTION_2		6119  /**/
#define ERR_V2XFAC_MANAGEMENTCONTAINERTYPE_VALIDITYDURATION_2		6133  /**/
#define ERR_V2XFAC_MANAGEMENTCONTAINERTYPE_TRANSMISSIONINTERVAL_2		6147  /**/
#define ERR_V2XFAC_MANAGEMENTCONTAINERTYPE_STATIONTYPE_2		6161  /**/
flag V2xFac_ManagementContainerType_IsConstraintValid(const V2xFac_ManagementContainerType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_MANAGEMENTCONTAINERTYPE		6169  /**/
#define ERR_UPER_ENCODE_V2XFAC_MANAGEMENTCONTAINERTYPE_ACTIONID_2		5910  /**/
#define ERR_UPER_ENCODE_V2XFAC_MANAGEMENTCONTAINERTYPE_DETECTIONTIME_2		5924  /**/
#define ERR_UPER_ENCODE_V2XFAC_MANAGEMENTCONTAINERTYPE_REFERENCETIME_2		5938  /**/
#define ERR_UPER_ENCODE_V2XFAC_MANAGEMENTCONTAINERTYPE_TERMINATION_2		5952  /**/
#define ERR_UPER_ENCODE_V2XFAC_MANAGEMENTCONTAINERTYPE_EVENTPOSITION_2		6092  /**/
#define ERR_UPER_ENCODE_V2XFAC_MANAGEMENTCONTAINERTYPE_RELEVANCEDISTANCE_2		6106  /**/
#define ERR_UPER_ENCODE_V2XFAC_MANAGEMENTCONTAINERTYPE_RELEVANCETRAFFICDIRECTION_2		6120  /**/
#define ERR_UPER_ENCODE_V2XFAC_MANAGEMENTCONTAINERTYPE_VALIDITYDURATION_2		6134  /**/
#define ERR_UPER_ENCODE_V2XFAC_MANAGEMENTCONTAINERTYPE_TRANSMISSIONINTERVAL_2		6148  /**/
#define ERR_UPER_ENCODE_V2XFAC_MANAGEMENTCONTAINERTYPE_STATIONTYPE_2		6162  /**/
#define V2xFac_ManagementContainerType_REQUIRED_BYTES_FOR_ENCODING       39 
#define V2xFac_ManagementContainerType_REQUIRED_BITS_FOR_ENCODING        305

flag V2xFac_ManagementContainerType_Encode(const V2xFac_ManagementContainerType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_MANAGEMENTCONTAINERTYPE		6170  /**/
#define ERR_UPER_DECODE_V2XFAC_MANAGEMENTCONTAINERTYPE_ACTIONID_2		5911  /**/
#define ERR_UPER_DECODE_V2XFAC_MANAGEMENTCONTAINERTYPE_DETECTIONTIME_2		5925  /**/
#define ERR_UPER_DECODE_V2XFAC_MANAGEMENTCONTAINERTYPE_REFERENCETIME_2		5939  /**/
#define ERR_UPER_DECODE_V2XFAC_MANAGEMENTCONTAINERTYPE_TERMINATION_2		5953  /**/
#define ERR_UPER_DECODE_V2XFAC_MANAGEMENTCONTAINERTYPE_EVENTPOSITION_2		6093  /**/
#define ERR_UPER_DECODE_V2XFAC_MANAGEMENTCONTAINERTYPE_RELEVANCEDISTANCE_2		6107  /**/
#define ERR_UPER_DECODE_V2XFAC_MANAGEMENTCONTAINERTYPE_RELEVANCETRAFFICDIRECTION_2		6121  /**/
#define ERR_UPER_DECODE_V2XFAC_MANAGEMENTCONTAINERTYPE_VALIDITYDURATION_2		6135  /**/
#define ERR_UPER_DECODE_V2XFAC_MANAGEMENTCONTAINERTYPE_TRANSMISSIONINTERVAL_2		6149  /**/
#define ERR_UPER_DECODE_V2XFAC_MANAGEMENTCONTAINERTYPE_STATIONTYPE_2		6163  /**/
flag V2xFac_ManagementContainerType_Decode(V2xFac_ManagementContainerType* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- V2xFac_DenMsgType --------------------------------------------*/
typedef struct {
    V2xFac_ManagementContainerType management;
    V2xFac_SituationContainerType situation;
    V2xFac_LocationContainerType location;
    V2xFac_AlacarteContainerType alacarte;

    struct {
        unsigned int situation:1;
        unsigned int location:1;
        unsigned int alacarte:1;
    } exist;

} V2xFac_DenMsgType;

void V2xFac_DenMsgType_Initialize(V2xFac_DenMsgType* pVal);

#define ERR_V2XFAC_DENMSGTYPE		5867  /**/
#define ERR_V2XFAC_DENMSGTYPE_MANAGEMENT_2		4509  /**/
#define ERR_V2XFAC_DENMSGTYPE_SITUATION_2		4733  /**/
#define ERR_V2XFAC_DENMSGTYPE_LOCATION_2		4957  /**/
#define ERR_V2XFAC_DENMSGTYPE_ALACARTE_2		5860  /**/
flag V2xFac_DenMsgType_IsConstraintValid(const V2xFac_DenMsgType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_DENMSGTYPE		5868  /**/
#define ERR_UPER_ENCODE_V2XFAC_DENMSGTYPE_MANAGEMENT_2		4510  /**/
#define ERR_UPER_ENCODE_V2XFAC_DENMSGTYPE_SITUATION_2		4734  /**/
#define ERR_UPER_ENCODE_V2XFAC_DENMSGTYPE_LOCATION_2		4958  /**/
#define ERR_UPER_ENCODE_V2XFAC_DENMSGTYPE_ALACARTE_2		5861  /**/
#define V2xFac_DenMsgType_REQUIRED_BYTES_FOR_ENCODING       3417 
#define V2xFac_DenMsgType_REQUIRED_BITS_FOR_ENCODING        27332

flag V2xFac_DenMsgType_Encode(const V2xFac_DenMsgType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_DENMSGTYPE		5869  /**/
#define ERR_UPER_DECODE_V2XFAC_DENMSGTYPE_MANAGEMENT_2		4511  /**/
#define ERR_UPER_DECODE_V2XFAC_DENMSGTYPE_SITUATION_2		4735  /**/
#define ERR_UPER_DECODE_V2XFAC_DENMSGTYPE_LOCATION_2		4959  /**/
#define ERR_UPER_DECODE_V2XFAC_DENMSGTYPE_ALACARTE_2		5862  /**/
flag V2xFac_DenMsgType_Decode(V2xFac_DenMsgType* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- V2xFac_DenmMessageRootType --------------------------------------------*/
typedef struct {
    V2xFac_ItsPduHeaderType itsPduHeader;
    V2xFac_DenMsgType denm;

} V2xFac_DenmMessageRootType;

void V2xFac_DenmMessageRootType_Initialize(V2xFac_DenmMessageRootType* pVal);

#define ERR_V2XFAC_DENMMESSAGEROOTTYPE		4201  /**/
#define ERR_V2XFAC_DENMMESSAGEROOTTYPE_ITSPDUHEADER_2		2521  /**/
#define ERR_V2XFAC_DENMMESSAGEROOTTYPE_DENM_2		4194  /**/
flag V2xFac_DenmMessageRootType_IsConstraintValid(const V2xFac_DenmMessageRootType* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_V2XFAC_DENMMESSAGEROOTTYPE		4202  /**/
#define ERR_UPER_ENCODE_V2XFAC_DENMMESSAGEROOTTYPE_ITSPDUHEADER_2		2522  /**/
#define ERR_UPER_ENCODE_V2XFAC_DENMMESSAGEROOTTYPE_DENM_2		4195  /**/
#define V2xFac_DenmMessageRootType_REQUIRED_BYTES_FOR_ENCODING       3423 
#define V2xFac_DenmMessageRootType_REQUIRED_BITS_FOR_ENCODING        27380

flag V2xFac_DenmMessageRootType_Encode(const V2xFac_DenmMessageRootType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_V2XFAC_DENMMESSAGEROOTTYPE		4203  /**/
#define ERR_UPER_DECODE_V2XFAC_DENMMESSAGEROOTTYPE_ITSPDUHEADER_2		2523  /**/
#define ERR_UPER_DECODE_V2XFAC_DENMMESSAGEROOTTYPE_DENM_2		4196  /**/
flag V2xFac_DenmMessageRootType_Decode(V2xFac_DenmMessageRootType* pVal, BitStream* pBitStrm, int* pErrCode);

//extern const asn1SccSint defaultValidity;
//extern const V2xFac_LongitudeType V2xFac_LongitudeType_v2XFAC_LONGITUDE_TYPE_ONE_MICRO_DEGREE_EAST;
//extern const V2xFac_LongitudeType V2xFac_LongitudeType_v2XFAC_LONGITUDE_TYPE_ONE_MICRO_DEGREE_WEST;
//extern const V2xFac_LongitudeType V2xFac_LongitudeType_v2XFAC_LONGITUDE_TYPE_UNAVAILABLE;
//extern const V2xFac_LatitudeType V2xFac_LatitudeType_v2XFAC_LATITUDE_TYPE_ONE_MICRO_DEGREE_NORTH;
//extern const V2xFac_LatitudeType V2xFac_LatitudeType_v2XFAC_LATITUDE_TYPE_ONE_MICRO_DEGREE_SOUTH;
//extern const V2xFac_LatitudeType V2xFac_LatitudeType_v2XFAC_LATITUDE_UNAVAILABLE;
//extern const V2xFac_AltitudeValueType V2xFac_AltitudeValueType_v2XFAC_ALTITUDE_VALUE_TYPE_REFERNCE_ELLIPSOID_SURFACE;
//extern const V2xFac_AltitudeValueType V2xFac_AltitudeValueType_v2XFAC_ALTITUDE_VALUE_TYPE_ONE_CENTIMETER;
//extern const V2xFac_AltitudeValueType V2xFac_AltitudeValueType_v2XFAC_ALTITUDE_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_DeltaLongitudeType V2xFac_DeltaLongitudeType_v2XFAC_DELTA_LONGITUDE_TYPE_ONE_MICRO_DEGREE_EAST;
//extern const V2xFac_DeltaLongitudeType V2xFac_DeltaLongitudeType_v2XFAC_DELTA_LONGITUDE_TYPE_ONE_MICRO_DEGREE_WEST;
//extern const V2xFac_DeltaLongitudeType V2xFac_DeltaLongitudeType_v2XFAC_DELTA_LONGITUDE_TYPE_UNAVAILABLE;
//extern const V2xFac_DeltaLatitudeType V2xFac_DeltaLatitudeType_v2XFAC_DELTA_LATITUDE_TYPE_ONE_MICRO_DEGREE_NORTH;
//extern const V2xFac_DeltaLatitudeType V2xFac_DeltaLatitudeType_v2XFAC_DELTA_LATITUDE_TYPE_ONE_MICRO_DEGREE_SOUTH;
//extern const V2xFac_DeltaLatitudeType V2xFac_DeltaLatitudeType_v2XFAC_DELTA_LATITUDE_TYPE_UNAVAILABLE;
//extern const V2xFac_DeltaAltitudeType V2xFac_DeltaAltitudeType_v2XFAC_DELTA_ALTITUDE_TYPE_ONE_CENTIMETER_UP;
//extern const V2xFac_DeltaAltitudeType V2xFac_DeltaAltitudeType_v2XFAC_DELTA_ALTITUDE_TYPE_ONE_CENTIMETER_DOWN;
//extern const V2xFac_DeltaAltitudeType V2xFac_DeltaAltitudeType_v2XFAC_DELTA_ALTITUDE_TYPE_UNAVAILABLE;
//extern const V2xFac_PathDeltaTimeType V2xFac_PathDeltaTimeType_v2XFAC_PATH_DELTA_TIME_TYPE_TEN_MILLI_SECONDS_PAST;
//extern const V2xFac_PtActivationTypeType V2xFac_PtActivationTypeType_v2XFAC_PT_ACTIVATION_TYPE_TYPE_UNDEFINED_CODING_TYPE;
//extern const V2xFac_PtActivationTypeType V2xFac_PtActivationTypeType_v2XFAC_PT_ACTIVATION_TYPE_TYPE_R09_16_CODING_TYPE;
//extern const V2xFac_PtActivationTypeType V2xFac_PtActivationTypeType_v2XFAC_PT_ACTIVATION_TYPE_TYPE_VDV_50149_CODING_TYPE;
//extern const V2xFac_SemiAxisLengthType V2xFac_SemiAxisLengthType_v2XFAC_SEMI_AXIS_LENGTH_TYPE_ONE_CENTIMETER;
//extern const V2xFac_SemiAxisLengthType V2xFac_SemiAxisLengthType_v2XFAC_SEMI_AXIS_LENGTH_TYPE_OUT_OF_RANGE;
//extern const V2xFac_SemiAxisLengthType V2xFac_SemiAxisLengthType_v2XFAC_SEMI_AXIS_LENGTH_TYPE_UNAVAILABLE;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_RESERVED;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_TRAFFIC_CONDITION;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_ACCIDENT;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_ROAD_WORKS;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_ADVERSE_WEATHER_CONDITION_ADHESION;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_HAZARDOUS_LOCATION_SURFACE_CONDITION;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_HAZARDOUS_LOCATION_OBSTACLE_ONT_THE_ROAD;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_HAZARDOUS_LOCATION_ANIMAL_ON_THE_ROAD;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_HAZARDOUS_LOCATION_HUMAN_ON_THE_ROAD;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_WRONG_WAY_DRIVING;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_RESCUE_AND_RECOVERY_WORK_IN_PROGRESS;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_ADVERSE_WEATHER_CONDITION_VISIBILITY;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_ADVERSE_WEATHER_CONDITION_PRECIPTION;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_SLOW_VEHICLE;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_DANGEROUS_END_OF_QUEUE;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_VEHICLE_BREAK_DOWN;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_POST_CRASH;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_HUMAN_PROBLEM;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_STATIONARY_VEHICLE;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_EMERGENCY_VEHICLE_APPROACHING;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_HAZARDOUS_LOCATION_DANGEROUS_CURVE;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_COLLISION_RISK;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_SIGNAL_VIOLATION;
//extern const V2xFac_CauseCodeTypeType V2xFac_CauseCodeTypeType_v2XFAC_CAUSE_CODE_TYPE_TYPE_DANGEROUS_SITUATION;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_INCREASED_VOLUME_OF_TRAFFIC;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_TRAFFIC_JAM_SLOWLY_INCREASING;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_TRAFFIC_JAM_INCREASING;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_TRAFFIC_JAM_STRONGLY_INCREASING;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_TRAFFIC_STATIONERY;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_TRAFFIC_JAM_SLIGHTLY_DECREASING;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_TRAFFIC_JAM_DECREASING;
//extern const V2xFac_TrafficConditionSubCauseCodeType V2xFac_TrafficConditionSubCauseCodeType_v2XFAC_TRAFFIC_CONDITION_SUB_CAUSE_CODE_TYPE_TRAFFIC_JAM_STRONGLY_DECREASING;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_MULTI_VEHICLE_ACCIDENT;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_HEAVY_ACCIDENT;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_ACCIDENT_INVOLVING_LORRY;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_ACCIDENT_INVOLVING_BUS;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_ACCIDENT_INVOLVING_HAZARDOUS_MATERIALS;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_ACCIDENT_ON_OPPOSITE_LANE;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_UNSECURED_ACCIDENT;
//extern const V2xFac_AccidentSubCauseCodeType V2xFac_AccidentSubCauseCodeType_v2XFAC_ACCIDENT_SUB_CAUSE_CODE_TYPE_ASSISTANCE_REQUESTED;
//extern const V2xFac_RoadworksSubCauseCodeType V2xFac_RoadworksSubCauseCodeType_v2XFAC_ROAD_WORKS_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_RoadworksSubCauseCodeType V2xFac_RoadworksSubCauseCodeType_v2XFAC_ROAD_WORKS_SUB_CAUSE_CODE_TYPE_MAJOR_ROAD_WORKS;
//extern const V2xFac_RoadworksSubCauseCodeType V2xFac_RoadworksSubCauseCodeType_v2XFAC_ROAD_WORKS_SUB_CAUSE_CODE_TYPE_ROAD_MARKING_WORK;
//extern const V2xFac_RoadworksSubCauseCodeType V2xFac_RoadworksSubCauseCodeType_v2XFAC_ROAD_WORKS_SUB_CAUSE_CODE_TYPE_SLOW_MOVING_ROAD_MAINTENANCE;
//extern const V2xFac_RoadworksSubCauseCodeType V2xFac_RoadworksSubCauseCodeType_v2XFAC_ROAD_WORKS_SUB_CAUSE_CODE_TYPE_SHORT_TERM_STATIONARY_ROADWORKS;
//extern const V2xFac_RoadworksSubCauseCodeType V2xFac_RoadworksSubCauseCodeType_v2XFAC_ROAD_WORKS_SUB_CAUSE_CODE_TYPE_STREET_CLEANING;
//extern const V2xFac_RoadworksSubCauseCodeType V2xFac_RoadworksSubCauseCodeType_v2XFAC_ROAD_WORKS_SUB_CAUSE_CODE_TYPE_WINTER_SERVICE;
//extern const V2xFac_HumanPresenceOnTheRoadSubCauseCodeType V2xFac_HumanPresenceOnTheRoadSubCauseCodeType_v2XFAC_HUMAN_PRESENCE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_HumanPresenceOnTheRoadSubCauseCodeType V2xFac_HumanPresenceOnTheRoadSubCauseCodeType_v2XFAC_HUMAN_PRESENCE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_CHILDREN_ON_ROADWAY;
//extern const V2xFac_HumanPresenceOnTheRoadSubCauseCodeType V2xFac_HumanPresenceOnTheRoadSubCauseCodeType_v2XFAC_HUMAN_PRESENCE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_CYCLIST_ON_ROADWAY;
//extern const V2xFac_HumanPresenceOnTheRoadSubCauseCodeType V2xFac_HumanPresenceOnTheRoadSubCauseCodeType_v2XFAC_HUMAN_PRESENCE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_MOTORCYCLIST_ON_ROADWAY;
//extern const V2xFac_WrongWayDrivingSubCauseCodeType V2xFac_WrongWayDrivingSubCauseCodeType_v2XFAC_WRONGWAY_DRIVING_SUB_CAUSECODE_TYPE_UNAVAILABLE;
//extern const V2xFac_WrongWayDrivingSubCauseCodeType V2xFac_WrongWayDrivingSubCauseCodeType_v2XFAC_WRONGWAY_DRIVING_SUB_CAUSECODE_TYPE_WRONG_LANE;
//extern const V2xFac_WrongWayDrivingSubCauseCodeType V2xFac_WrongWayDrivingSubCauseCodeType_v2XFAC_WRONGWAY_DRIVING_SUB_CAUSECODE_TYPE_WRONG_DIRECTION;
//extern const V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_TYPE_STRONG_WINDS;
//extern const V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_TYPE_DAMAGING_HAIL;
//extern const V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_TYPE_HURRICANE;
//extern const V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_TYPE_THUNDER_STORM;
//extern const V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_TYPE_TORNADO;
//extern const V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType V2xFac_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_TYPE_BLIZZARD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_HEAVY_FROST_ON_ROAD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_FUEL_ON_ROAD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_MUD_ON_ROAD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_SNOW_ON_ROAD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_ICE_ON_ROAD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_BLACK_ICE_ON_ROAD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_OIL_ON_ROAD;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_LOOSE_CHIPPINGS;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_INSTANT_BLACK_ICE;
//extern const V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType V2xFac_AdverseWeatherCondition_AdhesionSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_ADHESION_SUB_CAUSE_CODE_TYPE_ROADS_SALTED;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_FOG;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_SMOKE;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_HEAVY_SNOW_FALL;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_HEAVY_RAIN;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_HEAVY_HAIL;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_LOW_SUN_GLARE;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_SAND_STORMS;
//extern const V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType V2xFac_AdverseWeatherCondition_VisibilitySubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_VISIBILITY_SUB_CAUSE_CODE_TYPE_SWARMS_OF_INSECTS;
//extern const V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_PRECIPITATION_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_PRECIPITATION_SUB_CAUSE_CODE_TYPE_HEAVY_RAIN;
//extern const V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_PRECIPITATION_SUB_CAUSE_CODE_TYPE_HEAVY_SNOW_FALL;
//extern const V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType V2xFac_AdverseWeatherCondition_PrecipitationSubCauseCodeType_v2XFAC_ADVERSE_WEATHER_CONDITION_PRECIPITATION_SUB_CAUSE_CODE_TYPE_SOFT_HAIL;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_MAINTENANCE_VEHICLE;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_VEHICLES_SLOWING_TO_LOOK_AT_ACCIDENT;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_ABNORMAL_LOAD;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_ABNORMAL_WIDE_LOAD;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_CONVOY;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_SNOW_PLOUGH;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_DEICING;
//extern const V2xFac_SlowVehicleSubCauseCodeType V2xFac_SlowVehicleSubCauseCodeType_v2XFAC_SLOW_VEHICLE_SUB_CAUSE_CODE_TYPE_SALTING_VEHICLES;
//extern const V2xFac_StationaryVehicleSubCauseCodeType V2xFac_StationaryVehicleSubCauseCodeType_v2XFAC_STATIONARY_VEHICLE_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_StationaryVehicleSubCauseCodeType V2xFac_StationaryVehicleSubCauseCodeType_v2XFAC_STATIONARY_VEHICLE_SUB_CAUSE_CODE_TYPE_HUMAN_PROBLEM;
//extern const V2xFac_StationaryVehicleSubCauseCodeType V2xFac_StationaryVehicleSubCauseCodeType_v2XFAC_STATIONARY_VEHICLE_SUB_CAUSE_CODE_TYPE_VEHICLE_BREAKDOWN;
//extern const V2xFac_StationaryVehicleSubCauseCodeType V2xFac_StationaryVehicleSubCauseCodeType_v2XFAC_STATIONARY_VEHICLE_SUB_CAUSE_CODE_TYPE_POST_CRASH;
//extern const V2xFac_StationaryVehicleSubCauseCodeType V2xFac_StationaryVehicleSubCauseCodeType_v2XFAC_STATIONARY_VEHICLE_SUB_CAUSE_CODE_TYPE_PUBLIC_TRANSPORT_STOP;
//extern const V2xFac_StationaryVehicleSubCauseCodeType V2xFac_StationaryVehicleSubCauseCodeType_v2XFAC_STATIONARY_VEHICLE_SUB_CAUSE_CODE_TYPE_CARRYING_DANGEROUS_GOODS;
//extern const V2xFac_HumanProblemSubCauseCodeType V2xFac_HumanProblemSubCauseCodeType_v2XFAC_HUMAN_PROBLEM_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_HumanProblemSubCauseCodeType V2xFac_HumanProblemSubCauseCodeType_v2XFAC_HUMAN_PROBLEM_SUB_CAUSE_CODE_TYPE_GLYCEMIA_PROBLEM;
//extern const V2xFac_HumanProblemSubCauseCodeType V2xFac_HumanProblemSubCauseCodeType_v2XFAC_HUMAN_PROBLEM_SUB_CAUSE_CODE_TYPE_HEART_PROBLEM;
//extern const V2xFac_EmergencyVehicleApproachingSubCauseCodeType V2xFac_EmergencyVehicleApproachingSubCauseCodeType_v2XFAC_EMERGENCY_VEHICLE_APPROACHING_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_EmergencyVehicleApproachingSubCauseCodeType V2xFac_EmergencyVehicleApproachingSubCauseCodeType_v2XFAC_EMERGENCY_VEHICLE_APPROACHING_SUB_CAUSE_CODE_TYPE_EMERGENCY_VEHICLE_APPROACHING;
//extern const V2xFac_EmergencyVehicleApproachingSubCauseCodeType V2xFac_EmergencyVehicleApproachingSubCauseCodeType_v2XFAC_EMERGENCY_VEHICLE_APPROACHING_SUB_CAUSE_CODE_TYPE_PRIORITIZED_VEHICLE_APPROACHING;
//extern const V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_DANGEROUS_CURVE_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_DANGEROUS_CURVE_SUB_CAUSE_CODE_TYPE_DANGEROUS_LEFT_TURN_CURVE;
//extern const V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_DANGEROUS_CURVE_SUB_CAUSE_CODE_TYPE_DANGEROUS_RIGHT_TURN_CURVE;
//extern const V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_DANGEROUS_CURVE_SUB_CAUSE_CODE_TYPE_MULTIPLE_CURVES_STARTING_WITH_UNKNOWN_TURNING_DIRECTION;
//extern const V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_DANGEROUS_CURVE_SUB_CAUSE_CODE_TYPE_MULTIPLE_CURVES_STARTING_WITH_LEFT_TURN;
//extern const V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType V2xFac_HazardousLocation_DangerousCurveSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_DANGEROUS_CURVE_SUB_CAUSE_CODE_TYPE_MULTIPLE_CURVES_STARTING_WITH_RIGHT_TURN;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_ROCKFALLS;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_EARTHQUAKE_DAMAGE;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_SEWER_COLLAPSE;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_SUBSIDENCE;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_SNOW_DRIFTS;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_STORM_DAMAGE;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_BURST_PIPE;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_VOLCANO_ERUPTION;
//extern const V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType V2xFac_HazardousLocation_SurfaceConditionSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_SURFACE_CONDITION_SUB_CAUSE_CODE_TYPE_FALLING_ICE;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_SHED_LOAD;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_PARTS_OF_VEHICLES;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_PARTS_OF_TYRES;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_BIG_OBJECTS;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_FALLEN_TREES;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_HUB_CAPS;
//extern const V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_ObstacleOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_OBSTACLE_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_WAITING_VEHICLES;
//extern const V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_ANIMAL_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_ANIMAL_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_WILD_ANIMALS;
//extern const V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_ANIMAL_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_HERD_OF_ANIMALS;
//extern const V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_ANIMAL_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_SMALL_ANIMALS;
//extern const V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType V2xFac_HazardousLocation_AnimalOnTheRoadSubCauseCodeType_v2XFAC_HAZARDOUS_LOCATION_ANIMAL_ON_THE_ROAD_SUB_CAUSE_CODE_TYPE_LARGE_ANIMALS;
//extern const V2xFac_CollisionRiskSubCauseCodeType V2xFac_CollisionRiskSubCauseCodeType_v2XFAC_COLLISION_RISK_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_CollisionRiskSubCauseCodeType V2xFac_CollisionRiskSubCauseCodeType_v2XFAC_COLLISION_RISK_SUB_CAUSE_CODE_TYPE_LONGITUDINAL_COLLISION_RISK;
//extern const V2xFac_CollisionRiskSubCauseCodeType V2xFac_CollisionRiskSubCauseCodeType_v2XFAC_COLLISION_RISK_SUB_CAUSE_CODE_TYPE_CROSSING_COLLISION_RISK;
//extern const V2xFac_CollisionRiskSubCauseCodeType V2xFac_CollisionRiskSubCauseCodeType_v2XFAC_COLLISION_RISK_SUB_CAUSE_CODE_TYPE_LATERAL_COLLISION_RISK;
//extern const V2xFac_CollisionRiskSubCauseCodeType V2xFac_CollisionRiskSubCauseCodeType_v2XFAC_COLLISION_RISK_SUB_CAUSE_CODE_TYPE_VULNERABLE_ROAD_USER;
//extern const V2xFac_SignalViolationSubCauseCodeType V2xFac_SignalViolationSubCauseCodeType_v2XFAC_SIGNAL_VIOLATION_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_SignalViolationSubCauseCodeType V2xFac_SignalViolationSubCauseCodeType_v2XFAC_SIGNAL_VIOLATION_SUB_CAUSE_CODE_TYPE_STOP_SIGN_VIOLATION;
//extern const V2xFac_SignalViolationSubCauseCodeType V2xFac_SignalViolationSubCauseCodeType_v2XFAC_SIGNAL_VIOLATION_SUB_CAUSE_CODE_TYPE_TRAFFIC_LIGHT_VIOLATION;
//extern const V2xFac_SignalViolationSubCauseCodeType V2xFac_SignalViolationSubCauseCodeType_v2XFAC_SIGNAL_VIOLATION_SUB_CAUSE_CODE_TYPE_TURNING_REGULATION_VIOLATION;
//extern const V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType_v2XFAC_RESCUE_AND_RECOVERY_WORK_IN_PROGRESS_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType_v2XFAC_RESCUE_AND_RECOVERY_WORK_IN_PROGRESS_SUB_CAUSE_CODE_TYPE_EMERGENCY_VEHICLES;
//extern const V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType_v2XFAC_RESCUE_AND_RECOVERY_WORK_IN_PROGRESS_SUB_CAUSE_CODE_TYPE_RESCUE_HELICOPTER_LANDING;
//extern const V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType_v2XFAC_RESCUE_AND_RECOVERY_WORK_IN_PROGRESS_SUB_CAUSE_CODE_TYPE_POLICE_ACTIVITY_ONGOING;
//extern const V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType_v2XFAC_RESCUE_AND_RECOVERY_WORK_IN_PROGRESS_SUB_CAUSE_CODE_TYPE_MEDICAL_EMERGENCY_ONGOING;
//extern const V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType V2xFac_RescueAndRecoveryWorkInProgressSubCauseCodeType_v2XFAC_RESCUE_AND_RECOVERY_WORK_IN_PROGRESS_SUB_CAUSE_CODE_TYPE_CHILD_ABDUCTION_IN_PROGRESS;
//extern const V2xFac_DangerousEndOfQueueSubCauseCodeType V2xFac_DangerousEndOfQueueSubCauseCodeType_v2XFAC_DANGEROUS_END_OF_QUEUE_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_DangerousEndOfQueueSubCauseCodeType V2xFac_DangerousEndOfQueueSubCauseCodeType_v2XFAC_DANGEROUS_END_OF_QUEUE_SUB_CAUSE_CODE_TYPE_SUDDEN_END_OF_QUEUE;
//extern const V2xFac_DangerousEndOfQueueSubCauseCodeType V2xFac_DangerousEndOfQueueSubCauseCodeType_v2XFAC_DANGEROUS_END_OF_QUEUE_SUB_CAUSE_CODE_TYPE_QUEUE_OVER_HILL;
//extern const V2xFac_DangerousEndOfQueueSubCauseCodeType V2xFac_DangerousEndOfQueueSubCauseCodeType_v2XFAC_DANGEROUS_END_OF_QUEUE_SUB_CAUSE_CODE_TYPE_QUEUE_AROUND_BEND;
//extern const V2xFac_DangerousEndOfQueueSubCauseCodeType V2xFac_DangerousEndOfQueueSubCauseCodeType_v2XFAC_DANGEROUS_END_OF_QUEUE_SUB_CAUSE_CODE_TYPE_QUEUE_IN_TUNNEL;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_EMERGENCY_ELECTRONIC_BRAKE_ENGAGED;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_PRE_CRASH_SYSTEM_ENGAGED;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_ESP_ENGAGED;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_ABS_ENGAGED;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_AEB_ENGAGED;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_BRAKE_WARNING_ENGAGED;
//extern const V2xFac_DangerousSituationSubCauseCodeType V2xFac_DangerousSituationSubCauseCodeType_v2XFAC_DANGEROUS_SITUATION_SUB_CAUSE_CODE_TYPE_COLLISION_RISK_WARNING_ENGAGED;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_LACK_OF_FUEL;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_LACK_OF_BATTERY_POWER;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_ENGINE_PROBLEM;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_TRANSMISSION_PROBLEM;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_ENGINE_COOLING_PROBLEM;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_BRAKING_SYSTEM_PROBLEM;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_STEERING_PROBLEM;
//extern const V2xFac_VehicleBreakdownSubCauseCodeType V2xFac_VehicleBreakdownSubCauseCodeType_v2XFAC_VEHICLE_BREAK_DOWN_SUB_CAUSE_CODE_TYPE_TYRE_PUNCTURE;
//extern const V2xFac_PostCrashSubCauseCodeType V2xFac_PostCrashSubCauseCodeType_v2XFAC_POST_CRASH_SUB_CAUSE_CODE_TYPE_UNAVAILABLE;
//extern const V2xFac_PostCrashSubCauseCodeType V2xFac_PostCrashSubCauseCodeType_v2XFAC_POST_CRASH_SUB_CAUSE_CODE_TYPE_ACCIDENT_WITHOUT_E_CALL_TRIGGERED;
//extern const V2xFac_PostCrashSubCauseCodeType V2xFac_PostCrashSubCauseCodeType_v2XFAC_POST_CRASH_SUB_CAUSE_CODE_TYPE_ACCIDENT_WITH_E_CALL_MANUALLY_TRIGGERED;
//extern const V2xFac_PostCrashSubCauseCodeType V2xFac_PostCrashSubCauseCodeType_v2XFAC_POST_CRASH_SUB_CAUSE_CODE_TYPE_ACCIDENT_WITH_E_CALL_AUTOMATICALLY_TRIGGERED;
//extern const V2xFac_PostCrashSubCauseCodeType V2xFac_PostCrashSubCauseCodeType_v2XFAC_POST_CRASH_SUB_CAUSE_CODE_TYPE_ACCIDENT_WITH_E_CALL_TRIGGER_ED_WITHOUT_ACCESS_TO_CELLULAR_NETWORK;
//extern const V2xFac_CurvatureValueType V2xFac_CurvatureValueType_v2XFAC_CURVATURE_VALUE_TYPE_STRAIGHT;
//extern const V2xFac_CurvatureValueType V2xFac_CurvatureValueType_v2XFAC_CURVATURE_VALUE_TYPE_RECIPROCAL_OF_1_METER_RADIUS_TO_RIGHT;
//extern const V2xFac_CurvatureValueType V2xFac_CurvatureValueType_v2XFAC_CURVATURE_VALUE_TYPE_RECIPROCAL_OF_1_METER_RADIUS_TO_LEFT;
//extern const V2xFac_CurvatureValueType V2xFac_CurvatureValueType_v2XFAC_CURVATURE_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_HeadingValueType V2xFac_HeadingValueType_v2XFAC_HEADING_VALUE_TYPE_WGS_84_NORTH;
//extern const V2xFac_HeadingValueType V2xFac_HeadingValueType_v2XFAC_HEADING_VALUE_TYPE_WGS_84_EAST;
//extern const V2xFac_HeadingValueType V2xFac_HeadingValueType_v2XFAC_HEADING_VALUE_TYPE_WGS_84_SOUTH;
//extern const V2xFac_HeadingValueType V2xFac_HeadingValueType_v2XFAC_HEADING_VALUE_TYPE_WGS_84_WEST;
//extern const V2xFac_HeadingValueType V2xFac_HeadingValueType_v2XFAC_HEADING_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_HeadingConfidenceType V2xFac_HeadingConfidenceType_v2XFAC_HEADING_CONFIDENCE_TYPE_EQUAL_OR_WITHIN_ZERO_POINT_ONE_DEGREE;
//extern const V2xFac_HeadingConfidenceType V2xFac_HeadingConfidenceType_v2XFAC_HEADING_CONFIDENCE_TYPE_EQUAL_OR_WITHIN_ONE_DEGREE;
//extern const V2xFac_HeadingConfidenceType V2xFac_HeadingConfidenceType_v2XFAC_HEADING_CONFIDENCE_TYPE_OUT_OF_RANGE;
//extern const V2xFac_HeadingConfidenceType V2xFac_HeadingConfidenceType_v2XFAC_HEADING_CONFIDENCE_TYPE_UNAVAILABLE;
//extern const V2xFac_LanePositionType V2xFac_LanePositionType_v2XFAC_LANE_POSITION_TYPE_OFF_THE_ROAD;
//extern const V2xFac_LanePositionType V2xFac_LanePositionType_v2XFAC_LANE_POSITION_TYPE_HARD_SHOULDER;
//extern const V2xFac_LanePositionType V2xFac_LanePositionType_v2XFAC_LANE_POSITION_TYPE_OUTER_MOST_DRIVING_LANE;
//extern const V2xFac_LanePositionType V2xFac_LanePositionType_v2XFAC_LANE_POSITION_TYPE_SECOND_LANE_FROM_OUTSIDE;
//extern const V2xFac_PerformanceClassType V2xFac_PerformanceClassType_v2XFAC_PERFORMANCE_CLASS_TYPE_UNAVAILABLE;
//extern const V2xFac_PerformanceClassType V2xFac_PerformanceClassType_v2XFAC_PERFORMANCE_CLASS_TYPE_PERFORMANCE_CLASS_A;
//extern const V2xFac_PerformanceClassType V2xFac_PerformanceClassType_v2XFAC_PERFORMANCE_CLASS_TYPE_PERFORMANCE_CLASS_B;
//extern const V2xFac_SpeedValueType V2xFac_SpeedValueType_v2XFAC_SPEED_VALUE_TYPE_STANDSTILL;
//extern const V2xFac_SpeedValueType V2xFac_SpeedValueType_v2XFAC_SPEED_VALUE_TYPE_ONE_CENTIMETER_PER_SEC;
//extern const V2xFac_SpeedValueType V2xFac_SpeedValueType_v2XFAC_SPEED_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_SpeedConfidenceType V2xFac_SpeedConfidenceType_v2XFAC_SPEED_CONFIDENCE_TYPE_EQUAL_OR_WITHIN_ONE_CENTIMETER_PER_SEC;
//extern const V2xFac_SpeedConfidenceType V2xFac_SpeedConfidenceType_v2XFAC_SPEED_CONFIDENCE_TYPE_EQUAL_OR_WITHIN_ONE_METER_PER_SEC;
//extern const V2xFac_SpeedConfidenceType V2xFac_SpeedConfidenceType_v2XFAC_SPEED_CONFIDENCE_TYPE_OUT_OF_RANGE;
//extern const V2xFac_SpeedConfidenceType V2xFac_SpeedConfidenceType_v2XFAC_SPEED_CONFIDENCE_TYPE_UNAVAILABLE;
//extern const V2xFac_VehicleMassType V2xFac_VehicleMassType_v2XFAC_VEHICLE_MASS_TYPE_HUNDRED_KG;
//extern const V2xFac_VehicleMassType V2xFac_VehicleMassType_v2XFAC_VEHICLE_MASS_TYPE_UNAVAILABLE;
//extern const V2xFac_LongitudinalAccelerationValueType V2xFac_LongitudinalAccelerationValueType_v2XFAC_LONGITUDINAL_ACCELERATION_VALUE_TYPE_POINT_ONE_METER_PER_SEC_SQUARED_FORWARD;
//extern const V2xFac_LongitudinalAccelerationValueType V2xFac_LongitudinalAccelerationValueType_v2XFAC_LONGITUDINAL_ACCELERATION_VALUE_TYPE_POINT_ONE_METER_PER_SEC_SQUARED_BACKWARD;
//extern const V2xFac_LongitudinalAccelerationValueType V2xFac_LongitudinalAccelerationValueType_v2XFAC_LONGITUDINAL_ACCELERATION_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_AccelerationConfidenceType V2xFac_AccelerationConfidenceType_v2XFAC_ACCELERATION_CONFIDENCE_TYPE_POINT_ONE_METER_PER_SEC_SQUARED;
//extern const V2xFac_AccelerationConfidenceType V2xFac_AccelerationConfidenceType_v2XFAC_ACCELERATION_CONFIDENCE_TYPE_OUT_OF_RANGE;
//extern const V2xFac_AccelerationConfidenceType V2xFac_AccelerationConfidenceType_v2XFAC_ACCELERATION_CONFIDENCE_TYPE_UNAVAILABLE;
//extern const V2xFac_LateralAccelerationValueType V2xFac_LateralAccelerationValueType_v2XFAC_LATERAL_ACCELERATION_VALUE_TYPE_POINT_ONE_METER_PER_SEC_SQUARED_TO_RIGHT;
//extern const V2xFac_LateralAccelerationValueType V2xFac_LateralAccelerationValueType_v2XFAC_LATERAL_ACCELERATION_VALUE_TYPE_POINT_ONE_METER_PER_SEC_SQUARED_TO_LEFT;
//extern const V2xFac_LateralAccelerationValueType V2xFac_LateralAccelerationValueType_v2XFAC_LATERAL_ACCELERATION_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_VerticalAccelerationValueType V2xFac_VerticalAccelerationValueType_v2XFAC_VERTICAL_ACCELERATION_VALUE_TYPE_POINT_ONE_METER_PER_SEC_SQUARED_UP;
//extern const V2xFac_VerticalAccelerationValueType V2xFac_VerticalAccelerationValueType_v2XFAC_VERTICAL_ACCELERATION_VALUE_TYPE_POINT_ONE_METER_PER_SEC_SQUARED_DOWN;
//extern const V2xFac_VerticalAccelerationValueType V2xFac_VerticalAccelerationValueType_v2XFAC_VERTICAL_ACCELERATION_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_UNKNOWN;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_PEDESTRIAN;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_CYCLIST;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_MOPED;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_MOTORCYCLE;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_PASSENGERCAR;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_BUS;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_LIGHTTRUCK;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_HEAVYTRUCK;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_TRAILER;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_SPECIALVEHICLES;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_TRAM;
//extern const V2xFac_StationTypeType V2xFac_StationTypeType_v2XFAC_ST_ROADSIDEUNIT;
//extern const V2xFac_HeightLonCarrType V2xFac_HeightLonCarrType_v2XFAC_HEIGHT_LON_CAR_R_TYPE_ONE_CENTIMETER;
//extern const V2xFac_HeightLonCarrType V2xFac_HeightLonCarrType_v2XFAC_HEIGHT_LON_CAR_R_TYPE_UNAVAILABLE;
//extern const V2xFac_PosLonCarrType V2xFac_PosLonCarrType_v2XFAC_POS_LON_CAR_R_TYPE_ONE_CENTIMETER;
//extern const V2xFac_PosLonCarrType V2xFac_PosLonCarrType_v2XFAC_POS_LON_CAR_R_TYPE_UNAVAILABLE;
//extern const V2xFac_PosPillarType V2xFac_PosPillarType_v2XFAC_POS_PILLAR_TYPE_TEN_CENTIMETERS;
//extern const V2xFac_PosPillarType V2xFac_PosPillarType_v2XFAC_POS_PILLAR_TYPE_UNAVAILABLE;
//extern const V2xFac_PosCentMassType V2xFac_PosCentMassType_v2XFAC_POS_CENT_MASS_TYPE_TEN_CENTIMETERS;
//extern const V2xFac_PosCentMassType V2xFac_PosCentMassType_v2XFAC_POS_CENT_MASS_TYPE_UNAVAILABLE;
//extern const V2xFac_SpeedLimitType V2xFac_SpeedLimitType_v2XFAC_SPEED_LIMIT_TYPE_ONE_KM_PER_HOUR;
//extern const V2xFac_TemperatureType V2xFac_TemperatureType_v2XFAC_TEMPERATURE_TYPE_EQUAL_OR_SMALLER_THAN_MINUS_60DEG;
//extern const V2xFac_TemperatureType V2xFac_TemperatureType_v2XFAC_TEMPERATURE_TYPE_ONE_DEGREE_CELSIUS;
//extern const V2xFac_TemperatureType V2xFac_TemperatureType_v2XFAC_TEMPERATURE_TYPE_EQUAL_OR_GREATER_THAN_67DEG;
//extern const V2xFac_WheelBaseVehicleType V2xFac_WheelBaseVehicleType_v2XFAC_WHEEL_BASE_VEHICLE_TYPE_TEN_CENTIMETERS;
//extern const V2xFac_WheelBaseVehicleType V2xFac_WheelBaseVehicleType_v2XFAC_WHEEL_BASE_VEHICLE_TYPE_UNAVAILABLE;
//extern const V2xFac_TurningRadiusType V2xFac_TurningRadiusType_v2XFAC_TURNING_RADIUS_TYPE_POINT_4_METERS;
//extern const V2xFac_TurningRadiusType V2xFac_TurningRadiusType_v2XFAC_TURNING_RADIUS_TYPE_UNAVAILABLE;
//extern const V2xFac_PosFrontAxType V2xFac_PosFrontAxType_v2XFAC_POS_FRONT_AX_TYPE_TEN_CENTIMETERS;
//extern const V2xFac_PosFrontAxType V2xFac_PosFrontAxType_v2XFAC_POS_FRONT_AX_TYPE_UNAVAILABLE;
//extern const V2xFac_VehicleLengthValueType V2xFac_VehicleLengthValueType_v2XFAC_VEHICLE_LENGTH_VALUE_TYPE_TEN_CENTIMETERS;
//extern const V2xFac_VehicleLengthValueType V2xFac_VehicleLengthValueType_v2XFAC_VEHICLE_LENGTH_VALUE_TYPE_OUT_OF_RANGE;
//extern const V2xFac_VehicleLengthValueType V2xFac_VehicleLengthValueType_v2XFAC_VEHICLE_LENGTH_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_VehicleWidthType V2xFac_VehicleWidthType_v2XFAC_VEHICLE_WIDTH_TYPE_TEN_CENTIMETERS;
//extern const V2xFac_VehicleWidthType V2xFac_VehicleWidthType_v2XFAC_VEHICLE_WIDTH_TYPE_OUT_OF_RANGE;
//extern const V2xFac_VehicleWidthType V2xFac_VehicleWidthType_v2XFAC_VEHICLE_WIDTH_TYPE_UNAVAILABLE;
//extern const V2xFac_InformationQualityType V2xFac_InformationQualityType_v2XFAC_INFORMATION_QUALITY_TYPE_UNAVAILABLE;
//extern const V2xFac_InformationQualityType V2xFac_InformationQualityType_v2XFAC_INFORMATION_QUALITY_TYPE_LOWEST;
//extern const V2xFac_InformationQualityType V2xFac_InformationQualityType_v2XFAC_INFORMATION_QUALITY_TYPE_HIGHEST;
//extern const V2xFac_SteeringWheelAngleValueType V2xFac_SteeringWheelAngleValueType_v2XFAC_STEERING_WHEEL_ANGLE_VALUE_TYPE_STRAIGHT;
//extern const V2xFac_SteeringWheelAngleValueType V2xFac_SteeringWheelAngleValueType_v2XFAC_STEERING_WHEEL_ANGLE_VALUE_TYPE_ONE_POINT_FIVE_DEGREES_TO_RIGHT;
//extern const V2xFac_SteeringWheelAngleValueType V2xFac_SteeringWheelAngleValueType_v2XFAC_STEERING_WHEEL_ANGLE_VALUE_TYPE_ONE_POINT_FIVE_DEGREES_TO_LEFT;
//extern const V2xFac_SteeringWheelAngleValueType V2xFac_SteeringWheelAngleValueType_v2XFAC_STEERING_WHEEL_ANGLE_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_SteeringWheelAngleConfidenceType V2xFac_SteeringWheelAngleConfidenceType_v2XFAC_STEERING_WHEEL_ANGLE_CONFIDENCE_TYPE_EQUAL_OR_WITH_IN_ONE_POINT_FIVE_DEGREE;
//extern const V2xFac_SteeringWheelAngleConfidenceType V2xFac_SteeringWheelAngleConfidenceType_v2XFAC_STEERING_WHEEL_ANGLE_CONFIDENCE_TYPE_OUT_OF_RANGE;
//extern const V2xFac_SteeringWheelAngleConfidenceType V2xFac_SteeringWheelAngleConfidenceType_v2XFAC_STEERING_WHEEL_ANGLE_CONFIDENCE_TYPE_UNAVAILABLE;
//extern const V2xFac_TimestampItsType V2xFac_TimestampItsType_v2XFAC_TIME_STAMP_ITS_TYPE_UTC_START_OF_2004;
//extern const V2xFac_TimestampItsType V2xFac_TimestampItsType_v2XFAC_TIME_STAMP_ITS_TYPE_ONE_MILLI_SEC_AFTER_UTC_START_OF_2004;
//extern const V2xFac_YawRateValueType V2xFac_YawRateValueType_v2XFAC_YAWRATE_VALUE_TYPE_STRAIGHT;
//extern const V2xFac_YawRateValueType V2xFac_YawRateValueType_v2XFAC_YAWRATE_VALUE_TYPE_DEGSEC_000_01_TO_RIGHT;
//extern const V2xFac_YawRateValueType V2xFac_YawRateValueType_v2XFAC_YAWRATE_VALUE_TYPE_DEGSEC_000_01_TO_LEFT;
//extern const V2xFac_YawRateValueType V2xFac_YawRateValueType_v2XFAC_YAWRATE_VALUE_TYPE_UNAVAILABLE;
//extern const V2xFac_TransmissionIntervalType V2xFac_TransmissionIntervalType_v2XFAC_TRANSMISSION_INTERVAL_TYPE_one_Milli_Second;
//extern const V2xFac_TransmissionIntervalType V2xFac_TransmissionIntervalType_v2XFAC_TRANSMISSION_INTERVAL_TYPE_ten_Seconds;
//extern const V2xFac_ValidityDurationType V2xFac_ValidityDurationType_v2XFAC_VALIDITY_DURATION_TYPE_TIME_OF_DETECTION;
//extern const V2xFac_ValidityDurationType V2xFac_ValidityDurationType_v2XFAC_VALIDITY_DURATION_TYPE_ONE_SECOND_AFTER_DETECTION;
//extern const V2xFac_NumberOfOccupantsType V2xFac_NumberOfOccupantsType_v2XFAC_NUMBER_OF_OCCUPANTS_TYPE_ONE_OCCUPANT;
//extern const V2xFac_NumberOfOccupantsType V2xFac_NumberOfOccupantsType_v2XFAC_NUMBER_OF_OCCUPANTS_TYPE_UNAVAILABLE;
//extern const V2xFac_ProtectedZoneRadiusType V2xFac_ProtectedZoneRadiusType_v2XFAC_PROTECTED_ZONE_RADIUS_TYPE_ONE_METER;

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif
