/**
 * @file tpl_app_interrupts.c
 *
 * @section descr File description
 *
 * Generated functions related to interrupts.
 *
 * Generated from application v2x
 * Automatically generated by goil on Sun Jul 03 13:33:16 2022
 * from root OIL file v2x.oil
 *
 * @section infos File informations
 *
 * $$Date$$
 * $$Rev$$
 * $$Author$$
 * $$URL$$
 */

#include "tpl_compiler.h"
#include "tpl_cortex_definitions.h"
#include "tpl_os_interrupt_kernel.h"
#include "cmsis_wrapper.h"


#define OS_START_SEC_CODE
#include "tpl_memmap.h"

/*=============================================================================
 * Initialize the priorities in the NVIC according to the priorities defined
 * in the OIL/ARXML file
 */
FUNC(void, OS_CODE) tpl_init_it_priority(void)
{
  /*
   * Init of ISR category 1 priorities
   */


  /* Init the priority of TIM4_IRQ */
  NVIC_SetPriority(TIM4_IRQ_Number, TIM4_IRQ_Priority);
}

/*=============================================================================
 * To disable the OS interrupts, the corresponding ICER
 * are set
 */
FUNC(void, OS_CODE) tpl_disable_os_interrupts(void)
{
}

/*=============================================================================
 * To enable the OS interrupts, the corresponding ISER
 * are set
 */
FUNC(void, OS_CODE) tpl_enable_os_interrupts(void)
{
}


#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/* End of file tpl_init_it_priority.c */
