/**
 * @file tpl_cortex_definitions.h
 *
 * @section descr File description
 *
 * Defines related to the cortex target platform
 *
 * Generated from application v2x
 * Automatically generated by goil on Wed Jun 29 16:18:33 2022
 * from root OIL file v2x.oil
 *
 * @section infos File informations
 *
 * $$Date$$
 * $$Rev$$
 * $$Author$$
 * $$URL$$
 */

#ifndef TPL_CORTEX_DEFINITIONS_H
#define TPL_CORTEX_DEFINITIONS_H
  
/*-----------------------------------------------------------------------------
 * File generated for target cortex/armv7em/stm32f429/stm32f4discovery
 * Number of priority bits :      4
 */
#define PRIO_BITS_IN_NVIC              4

/*
 * Priorities are unshifted and intended to be used in NVIC_SetPriority
 */
#define KERNEL_PRIO_UNSHIFTED        15
#define OS_ISR_PRIO_UNSHIFTED        15
#define ISR1_IT_PRIO_UNSHIFTED        1

/*
 * Priorities are shifted and intended to be stored in BASEPRI
 */
#define KERNEL_PRIO       240          /* Unshifted priority: 15     */
#define OS_ISR_PRIO       240          /* Unshifted priority: 15     */
#define ISR1_IT_PRIO       16          /* Unshifted priority: 1      */

/*
 * Priority of KERNEL_PRIO shifted to fit in SHPR2
 */
#define KERNEL_PRIO_SHPR2    0xF0000000

/*
 * Interrupt numbers for interrupt sources used by ISR
 */
#define EXTI0_IRQ_Number                        6
#define TIM4_IRQ_Number                        30

/*
 * Computed priorities for interrupt sources used by ISR category 1
 * Priorities are unshifted and intended to be used in NVIC_SetPriority
 */
#define EXTI0_IRQ_Priority                     14
#define TIM4_IRQ_Priority                      14

/* TPL_CORTEX_DEFINITIONS_H */
#endif

/* End of file tpl_cortex_definitions.h */
